### ISSUE TITLE
Red nodes 

### ISSUE THREAD

**Issue by abozahran** [kijai/ComfyUI-HunyuanVideoWrapper#10]
I tried to manually install HunyuanVideoWrapper manually by downloading the zip file and extract it in custom nodes
and did pip install -r requirements.txt correctlly without errors and after restart comfy ui is still get red nodes

![image](https://github.com/user-attachments/assets/cf906def-68ea-4015-90ea-f39fade6df5c)

**Comment by kijai** [comment]
Check the ComfyUI startup log for import errors, there should be something like "module not found".

**Comment by kijai** [comment]
Looks like you would need to update diffusers

**Comment by abozahran** [comment]
> Looks like you would need to update diffusers

can i just pip install diffusers inside the HunyuanVideoWrapper node?

**Comment by abozahran** [comment]
I get this after pip 
Requirement already satisfied: diffusers in c:\users\zahran\appdata\local\programs\python\python310\lib\site-packages (0.31.0)

**Comment by abozahran** [comment]
by the way  ( the official ltx video workflow give me red nodes too but another workflow online i found working with no problem but with different nodes )

**Comment by kijai** [comment]
> > Looks like you would need to update diffusers
> 
> can i just pip install diffusers inside the HunyuanVideoWrapper node?

it looks like you are using your system wide python environment to run ComfyUI, in that case it would indeed be just 
`pip install -U diffusers`

**Comment by abozahran** [comment]
C:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper>python -m venv venv\

C:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper>venv\Scripts\activate.bat

(venv) C:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper>python -m pip install -r requirements.txt
Collecting accelerate>=1.1.1
  Downloading accelerate-1.1.1-py3-none-any.whl (333 kB)
     ---------------------------------------- 333.2/333.2 kB 2.1 MB/s eta 0:00:00
Collecting diffusers>=0.31.0
  Using cached diffusers-0.31.0-py3-none-any.whl (2.9 MB)
Collecting transformers>=4.39.3
  Downloading transformers-4.46.3-py3-none-any.whl (10.0 MB)
     ---------------------------------------- 10.0/10.0 MB 3.7 MB/s eta 0:00:00
Collecting psutil
  Downloading psutil-6.1.0-cp37-abi3-win_amd64.whl (254 kB)
     ---------------------------------------- 254.2/254.2 kB 3.1 MB/s eta 0:00:00
Collecting numpy<3.0.0,>=1.17
  Using cached numpy-2.1.3-cp310-cp310-win_amd64.whl (12.9 MB)
Collecting pyyaml
  Using cached PyYAML-6.0.2-cp310-cp310-win_amd64.whl (161 kB)
Collecting packaging>=20.0
  Using cached packaging-24.2-py3-none-any.whl (65 kB)
Collecting huggingface-hub>=0.21.0
  Using cached huggingface_hub-0.26.3-py3-none-any.whl (447 kB)
Collecting safetensors>=0.4.3
  Using cached safetensors-0.4.5-cp310-none-win_amd64.whl (285 kB)
Collecting torch>=1.10.0
  Downloading torch-2.5.1-cp310-cp310-win_amd64.whl (203.1 MB)
     ---------------------------------------- 203.1/203.1 MB 3.1 MB/s eta 0:00:00
Collecting requests
  Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Collecting filelock
  Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Collecting Pillow
  Using cached pillow-11.0.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting regex!=2019.12.17
  Using cached regex-2024.11.6-cp310-cp310-win_amd64.whl (274 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Collecting tqdm>=4.27
  Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Collecting tokenizers<0.21,>=0.20
  Downloading tokenizers-0.20.3-cp310-none-win_amd64.whl (2.4 MB)
     ---------------------------------------- 2.4/2.4 MB 3.6 MB/s eta 0:00:00
Collecting fsspec>=2023.5.0
  Using cached fsspec-2024.10.0-py3-none-any.whl (179 kB)
Collecting typing-extensions>=3.7.4.3
  Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting jinja2
  Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Collecting networkx
  Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 3.3 MB/s eta 0:00:00
Collecting sympy==1.13.1
  Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ---------------------------------------- 6.2/6.2 MB 2.8 MB/s eta 0:00:00
Collecting mpmath<1.4,>=1.1.0
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting zipp>=3.20
  Using cached zipp-3.21.0-py3-none-any.whl (9.6 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.10-py3-none-any.whl (70 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.4.0-cp310-cp310-win_amd64.whl (102 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-3.0.2-cp310-cp310-win_amd64.whl (15 kB)
Installing collected packages: mpmath, zipp, urllib3, typing-extensions, sympy, safetensors, regex, pyyaml, psutil, Pillow, packaging, numpy, networkx, MarkupSafe, idna, fsspec, filelock, colorama, charset-normalizer, certifi, tqdm, requests, jinja2, importlib-metadata, torch, huggingface-hub, tokenizers, diffusers, accelerate, transformers
Successfully installed MarkupSafe-3.0.2 Pillow-11.0.0 accelerate-1.1.1 certifi-2024.8.30 charset-normalizer-3.4.0 colorama-0.4.6 diffusers-0.31.0 filelock-3.16.1 fsspec-2024.10.0 huggingface-hub-0.26.3 idna-3.10 importlib-metadata-8.5.0 jinja2-3.1.4 mpmath-1.3.0 networkx-3.4.2 numpy-2.1.3 packaging-24.2 psutil-6.1.0 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 safetensors-0.4.5 sympy-1.13.1 tokenizers-0.20.3 torch-2.5.1 tqdm-4.67.1 transformers-4.46.3 typing-extensions-4.12.2 urllib3-2.2.3 zipp-3.21.0

[notice] A new release of pip available: 22.3.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



THE PROBLEM STILL EXIST unfortunately

**Comment by kijai** [comment]
> C:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper>python -m venv venv\
> 
> C:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper>venv\Scripts\activate.bat
> 
> (venv) C:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper>python -m pip install -r requirements.txt Collecting accelerate>=1.1.1 Downloading accelerate-1.1.1-py3-none-any.whl (333 kB) ---------------------------------------- 333.2/333.2 kB 2.1 MB/s eta 0:00:00 Collecting diffusers>=0.31.0 Using cached diffusers-0.31.0-py3-none-any.whl (2.9 MB) Collecting transformers>=4.39.3 Downloading transformers-4.46.3-py3-none-any.whl (10.0 MB) ---------------------------------------- 10.0/10.0 MB 3.7 MB/s eta 0:00:00 Collecting psutil Downloading psutil-6.1.0-cp37-abi3-win_amd64.whl (254 kB) ---------------------------------------- 254.2/254.2 kB 3.1 MB/s eta 0:00:00 Collecting numpy<3.0.0,>=1.17 Using cached numpy-2.1.3-cp310-cp310-win_amd64.whl (12.9 MB) Collecting pyyaml Using cached PyYAML-6.0.2-cp310-cp310-win_amd64.whl (161 kB) Collecting packaging>=20.0 Using cached packaging-24.2-py3-none-any.whl (65 kB) Collecting huggingface-hub>=0.21.0 Using cached huggingface_hub-0.26.3-py3-none-any.whl (447 kB) Collecting safetensors>=0.4.3 Using cached safetensors-0.4.5-cp310-none-win_amd64.whl (285 kB) Collecting torch>=1.10.0 Downloading torch-2.5.1-cp310-cp310-win_amd64.whl (203.1 MB) ---------------------------------------- 203.1/203.1 MB 3.1 MB/s eta 0:00:00 Collecting requests Using cached requests-2.32.3-py3-none-any.whl (64 kB) Collecting filelock Using cached filelock-3.16.1-py3-none-any.whl (16 kB) Collecting Pillow Using cached pillow-11.0.0-cp310-cp310-win_amd64.whl (2.6 MB) Collecting regex!=2019.12.17 Using cached regex-2024.11.6-cp310-cp310-win_amd64.whl (274 kB) Collecting importlib-metadata Using cached importlib_metadata-8.5.0-py3-none-any.whl (26 kB) Collecting tqdm>=4.27 Using cached tqdm-4.67.1-py3-none-any.whl (78 kB) Collecting tokenizers<0.21,>=0.20 Downloading tokenizers-0.20.3-cp310-none-win_amd64.whl (2.4 MB) ---------------------------------------- 2.4/2.4 MB 3.6 MB/s eta 0:00:00 Collecting fsspec>=2023.5.0 Using cached fsspec-2024.10.0-py3-none-any.whl (179 kB) Collecting typing-extensions>=3.7.4.3 Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB) Collecting jinja2 Using cached jinja2-3.1.4-py3-none-any.whl (133 kB) Collecting networkx Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB) ---------------------------------------- 1.7/1.7 MB 3.3 MB/s eta 0:00:00 Collecting sympy==1.13.1 Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB) ---------------------------------------- 6.2/6.2 MB 2.8 MB/s eta 0:00:00 Collecting mpmath<1.4,>=1.1.0 Using cached mpmath-1.3.0-py3-none-any.whl (536 kB) Collecting colorama Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB) Collecting zipp>=3.20 Using cached zipp-3.21.0-py3-none-any.whl (9.6 kB) Collecting urllib3<3,>=1.21.1 Using cached urllib3-2.2.3-py3-none-any.whl (126 kB) Collecting idna<4,>=2.5 Using cached idna-3.10-py3-none-any.whl (70 kB) Collecting certifi>=2017.4.17 Using cached certifi-2024.8.30-py3-none-any.whl (167 kB) Collecting charset-normalizer<4,>=2 Using cached charset_normalizer-3.4.0-cp310-cp310-win_amd64.whl (102 kB) Collecting MarkupSafe>=2.0 Using cached MarkupSafe-3.0.2-cp310-cp310-win_amd64.whl (15 kB) Installing collected packages: mpmath, zipp, urllib3, typing-extensions, sympy, safetensors, regex, pyyaml, psutil, Pillow, packaging, numpy, networkx, MarkupSafe, idna, fsspec, filelock, colorama, charset-normalizer, certifi, tqdm, requests, jinja2, importlib-metadata, torch, huggingface-hub, tokenizers, diffusers, accelerate, transformers Successfully installed MarkupSafe-3.0.2 Pillow-11.0.0 accelerate-1.1.1 certifi-2024.8.30 charset-normalizer-3.4.0 colorama-0.4.6 diffusers-0.31.0 filelock-3.16.1 fsspec-2024.10.0 huggingface-hub-0.26.3 idna-3.10 importlib-metadata-8.5.0 jinja2-3.1.4 mpmath-1.3.0 networkx-3.4.2 numpy-2.1.3 packaging-24.2 psutil-6.1.0 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 safetensors-0.4.5 sympy-1.13.1 tokenizers-0.20.3 torch-2.5.1 tqdm-4.67.1 transformers-4.46.3 typing-extensions-4.12.2 urllib3-2.2.3 zipp-3.21.0
> 
> [notice] A new release of pip available: 22.3.1 -> 24.3.1 [notice] To update, run: python.exe -m pip install --upgrade pip
> 
> THE PROBLEM STILL EXIST unfortunately

Can you try:

`pip install -U jax`

**Comment by abozahran** [comment]
> pip install -U jax

I downloaded the portable version of comfy and it worked 
but i am gonna try jax for the main comfy folder i have
