### ISSUE TITLE
Usage of custom prompt template

### ISSUE THREAD

**Issue by wwwffbf** [kijai/ComfyUI-HunyuanVideoWrapper#102]
Is the text in the HunyuanVideo Custom Prompt Template node replacing the "user" here?
<|start_header_id|>user<|end_header_id|>

When I try to change something else it causes a black screen to be generated, such as removing "describe the video ......"

**Comment by kijai** [comment]
The whole text in the node is the default prompt template, as it is. You shouldn't change any of the special tokens, but you should be able to change the instructions, haven't played it with much, just enough to confirm it worked and changed the output. Some others experimented more, there's not been any consensus if it even should be edited though, it's there to experiment with.

**Comment by wwwffbf** [comment]
> The whole text in the node is the default prompt template, as it is. You shouldn't change any of the special tokens, but you should be able to change the instructions, haven't played it with much, just enough to confirm it worked and changed the output. Some others experimented more, there's not been any consensus if it even should be edited though, it's there to experiment with.

Thank you very much
When I changed the user to other prompts, such as the style setting: “CG animation, 3D render”, or the background setting “desolate Mars base”. It did have a positive effect on the output.
Also, do you have a better CLIP L recommendation? I tried a couple of CLIP versions from zer0int, but the results didn't change much. For example, I found that it can't distinguish camera zoom in and zoom out, and the generated result is always zoom in. But hunyuan's online version can understand it very well.
