### ISSUE TITLE
Negative prompts

### ISSUE THREAD

**Issue by DragonfruitQuirky** [kijai/ComfyUI-HunyuanVideoWrapper#104]
I see there is some code in there for negative prompting but it looks like you commented it out. Which I guess means it isn't working yet. Any ETA on when you will get around to it? And what was the problem you had with it?

**Comment by sd2530615** [comment]
there are negative prompts in early commit then kijai removes it from code, i guess it might not working .

**Comment by DragonfruitQuirky** [comment]
> > I see there is some code in there for negative prompting but it looks like you commented it out. Which I guess means it isn't working yet. Any ETA on when you will get around to it? And what was the problem you had with it?
> 
> The model they have released is a cfg distilled model, which doesn't use cfg and thus no negative prompt, just like Flux. For negative prompting we'd need the undistilled model, which would also then be twice as slow and use more memory though.

Oh they had an option for negative prompting on their huggingface sample. So now I am just confused lol. Anyway thanks for an answer!

**Comment by kijai** [comment]
> > > I see there is some code in there for negative prompting but it looks like you commented it out. Which I guess means it isn't working yet. Any ETA on when you will get around to it? And what was the problem you had with it?
> > 
> > 
> > The model they have released is a cfg distilled model, which doesn't use cfg and thus no negative prompt, just like Flux. For negative prompting we'd need the undistilled model, which would also then be twice as slow and use more memory though.
> 
> Oh they had an option for negative prompting on their github. So now I am just confused lol. Anyway thanks for an answer!

Yes the code can use both models, we just only have the cfg distilled version.
