### ISSUE TITLE
torch complie error

### ISSUE THREAD

**Issue by pondloso** [kijai/ComfyUI-HunyuanVideoWrapper#109]
It give me this error when i try to use it

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information You can suppress this exception and fall back to eager by setting: import torch._dynamo torch._dynamo.config.suppress_errors = True

i can gen with segattn just fine with triton install.

**Comment by Heetoprime** [comment]
Can you show your workflow? You're likely using Torch Compile node, but I can compile without it. Not sure how necessary it is tbh, you can check the workflow videos in README to get an idea of the workflow needed.

**Comment by pundabadu-1** [comment]
> It give me this error when i try to use it
> 
> Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information You can suppress this exception and fall back to eager by setting: import torch._dynamo torch._dynamo.config.suppress_errors = True
> 
> i can gen with segattn just fine with triton install.

same issue here

**Comment by plh1988** [comment]
in torch compile settings change last three compile options to false

**Comment by pondloso** [comment]
> in torch compile settings change last three compile options to false

Thank you .

**Comment by Tapyon** [comment]
NOT SURE IF THIS POST WILL HELPs, 
--------------------
https://www.reddit.com/r/StableDiffusion/comments/1h7hunp/how_to_run_hunyuanvideo_on_a_single_24gb_vram_card/
--------------------
but i dont get SAGATTENTION error and the other IMG WEIGHT error! 
changing the MODE ATTENTION  ==  "SDPA"

![Image](https://github.com/user-attachments/assets/09c9c42a-36cb-4545-bdbd-0deb47982742)

Now i have a triton error ! hehe! but i think is past that one...

**Comment by MonnaHaddid** [comment]
> in torch compile settings change last three compile options to false


How do you do this? In what file or where? Excuse my ignorance; I'm new to this.

**Comment by doudoumei** [comment]
> > 在 torch 编译设置中将最后三个编译选项更改为 false
> 
> 怎么做？在哪个文件里？或者在哪里？恕我无知，我对此还不熟
我也想知道。。。

**Comment by MasterCod2023** [comment]
> in torch compile settings change last three compile options to false

How do I do that? Where should I look? I'm new to this, thanks.

**Comment by doudoumei** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
