### ISSUE TITLE
model location

### ISSUE THREAD

**Issue by AlphaOmega1707** [kijai/ComfyUI-HunyuanVideoWrapper#110]
where does the model itself usually goes? i'm using extra_model_paths.yaml enabled and followed the tooltip for the "diffusion_models" folder within "models", but even so it doesn't seem to show up, "HyVideoModelLoader: - Value not in list"

**Comment by kijai** [comment]
The models in the HyVideoModelLoader are loaded exactly like any comfy diffusion_model, it shouldn't be any different.

**Comment by AlphaOmega1707** [comment]
so the usual checkpoints folder? i tried multiple folders and didn't seem to get it to show up

**Comment by AlphaOmega1707** [comment]
seems to have worked, thanks
