### ISSUE TITLE
DownloadAndLoadHyVideoTextEncoder `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models.

### ISSUE THREAD

**Issue by RuslanKuz** [kijai/ComfyUI-HunyuanVideoWrapper#112]
Hello! I get an error with lowram workflow:
"DownloadAndLoadHyVideoTextEncoder
`.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`."
I reinstalled bitsandbytes but the same issue.
What could possibly be wrong?

`Loading text encoder model (clipL) from: F:\AI\ComfyUI\ComfyUI\models\clip\clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: F:\AI\ComfyUI\ComfyUI\models\clip\clip-vit-large-patch14
Loading text encoder model (llm) from: F:\AI\ComfyUI\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:07<00:00,  1.97s/it]
!!! Exception during processing !!! `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 477, in loadmodel
    text_encoder = TextEncoder(
                   ^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 156, in __init__
    self.model, self.model_path = load_text_encoder(
                                  ^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 38, in load_text_encoder
    text_encoder = AutoModel.from_pretrained(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 4034, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "F:\AI\ComfyUI\python_embeded\Lib\site-packages\accelerate\big_modeling.py", line 498, in dispatch_model
    model.to(device)
  File "F:\AI\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 2883, in to
    raise ValueError(
ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.

Prompt executed in 8.80 seconds
`

![IMG_20241211_130210](https://github.com/user-attachments/assets/57485f1d-36f9-421f-a37a-e5d62ee587e4)

**Comment by kijai** [comment]
Update `transformers `and `accelerate `as well.

**Comment by RuslanKuz** [comment]
> Update `transformers `and `accelerate `as well.

Tried to update. But the same result

`F:\AI\ComfyUI\python_embeded>pip install transformers -U
Requirement already satisfied: transformers in c:\python310\lib\site-packages (4.47.0)
Requirement already satisfied: filelock in c:\python310\lib\site-packages (from transformers) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in c:\python310\lib\site-packages (from transformers) (0.26.5)
Requirement already satisfied: numpy>=1.17 in c:\python310\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\python310\lib\site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\python310\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\python310\lib\site-packages (from transformers) (2024.5.15)
Requirement already satisfied: requests in c:\python310\lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\python310\lib\site-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in c:\python310\lib\site-packages (from transformers) (0.4.3)
Requirement already satisfied: tqdm>=4.27 in c:\python310\lib\site-packages (from transformers) (4.66.4)
Requirement already satisfied: fsspec>=2023.5.0 in c:\python310\lib\site-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\python310\lib\site-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.8.0)
Requirement already satisfied: colorama in c:\python310\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python310\lib\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python310\lib\site-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\python310\lib\site-packages (from requests->transformers) (2024.7.4)`


And this is pip list:

`accelerate         1.2.0
bitsandbytes       0.45.0
certifi            2024.7.4
charset-normalizer 3.3.2
colorama           0.4.6
cpm-kernels        1.0.11
diffusers          0.31.0
einops             0.8.0
filelock           3.9.0
fsspec             2024.6.1
huggingface-hub    0.26.5
idna               3.7
importlib_metadata 8.0.0
jax                0.4.37
jaxlib             0.4.36
Jinja2             3.1.2
MarkupSafe         2.1.3
ml_dtypes          0.5.0
mpmath             1.3.0
networkx           3.2.1
nexfort            0.0.1.dev0
numpy              1.26.4
omegaconf          2.4.0.dev3
onediff            1.2.1.dev28
onediffx           1.2.1.dev28
onefx              0.0.3
opt_einsum         3.4.0
packaging          24.1
peppercorn         0.6
pi                 0.1.2
pillow             10.2.0
pip                24.3.1
protobuf           5.28.3
psutil             6.0.0
PyYAML             6.0.1
regex              2024.5.15
requests           2.32.3
safetensors        0.4.3
scipy              1.14.1
sentencepiece      0.2.0
setuptools         65.5.0
sympy              1.13.1
timm               1.0.11
tokenizers         0.21.0
torch              2.6.0.dev20240928+cu124
torchaudio         2.5.0.dev20240929+cu124
torchvision        0.20.0.dev20240929+cu124
tqdm               4.66.4
transformers       4.47.0
typing_extensions  4.8.0
urllib3            2.2.2
zipp               3.19.2`

**Comment by kijai** [comment]
Hmmm no idea then, I have the same versions of everything relevant... besides not using nightly torch currently.

**Comment by RuslanKuz** [comment]
> Hmmm no idea then, I have the same versions of everything relevant... besides not using nightly torch currently.

Ok, thanks! I will try to install torch 2.5.1

**Comment by kijai** [comment]
> fix:
> 
> ```
> python_embeded\python.exe -m pip install bitsandbytes
> python_embeded\python.exe -m pip uninstall accelerate
> python_embeded\python.exe -m pip install accelerate==1.1.1
> ```
> 
> accelerate 1.2.0 gives the error

That's very odd as it's working fine for me on 1.2.0.

**Comment by RuslanKuz** [comment]
> python.exe -m pip install accelerate==1.1.1

It's surprising and really working now! Thank you!

**Comment by Ratinod** [comment]
> That's very odd as it's working fine for me on 1.2.0.

Linux? For Windows, many things related to neural networks is done on a residual basis.
I'm glad it was fixed at least this way, because many neural networks libraries are "Linux only" and developers are not interested in supporting other OS. Of course, I understand that development is primarily for Linux, so that in the future everything can be deployed on Linux services (most likely paid ones), and not for local use... 

> It's surprising and really working now! Thank you!

yeah, glad it helped

**Comment by kijai** [comment]
> > That's very odd as it's working fine for me on 1.2.0.
> 
> Linux? For Windows, many things related to neural networks is done on a residual basis. (Quite often, python code that works in Linux for some unknown reason does not work in Windows) I'm glad it was fixed at least this way, because many neural networks libraries are "Linux only" and developers are not interested in supporting other OS (They write code that works on Linux because they use linux themselves, and Windows is a matter of luck). Of course, I understand that development is primarily for Linux, so that in the future everything can be deployed on Linux services (most likely paid ones), and not for local use...
> 
> > It's surprising and really working now! Thank you!
> 
> yeah, glad it helped

Yeah on Windows, I would love to use Linux but you just outlined the reason I'm mostly not.

**Comment by Ratinod** [comment]
> on Windows

hmm... then why does 1.2.0 work for some and not for others? Is it really a matter of the versions of the packages that are required for accelerate?
```
datasets
diffusers
evaluate
torchdata>=0.8.0
torchpippy>=0.2.0
transformers
scipy
scikit-learn
tqdm
bitsandbytes
timm
numpy>=1.17,<3.0.0
packaging>=20.0
psutil
pyyaml
torch>=1.10.0
huggingface_hub>=0.21.0
safetensors>=0.4.3
```

**Comment by kijai** [comment]
Could also be about python version? I'm on 3.12.7

**Comment by Ratinod** [comment]
`python_embeded\python.exe --version`
Python 3.12.7
the same

**Comment by Ratinod** [comment]
some versions
`python_embeded\python.exe -m pip show diffusers`
Version: 0.31.0
`python_embeded\python.exe -m pip show transformers`
Version: 4.44.2
`python_embeded\python.exe -m pip show scipy`
Version: 1.14.1
`python_embeded\python.exe -m pip show scikit-learn`
Version: 1.5.2
`python_embeded\python.exe -m pip show tqdm`
Version: 4.66.5
`python_embeded\python.exe -m pip show bitsandbytes`
ersion: 0.45.1.dev0
`python_embeded\python.exe -m pip show timm`
Version: 1.0.11
`python_embeded\python.exe -m pip show numpy`
Version: 1.26.4
`python_embeded\python.exe -m pip show packaging`
Version: 23.2
`python_embeded\python.exe -m pip show psutil`
Version: 6.1.0
`python_embeded\python.exe -m pip show pyyaml`
Version: 6.0.2
`python_embeded\python.exe -m pip show torch`
Version: 2.5.1+cu124
`python_embeded\python.exe -m pip show huggingface_hub`
Version: 0.25.2
`python_embeded\python.exe -m pip show safetensors`
Version: 0.4.5

**Comment by Ratinod** [comment]
`python_embeded\python.exe -m pip list`
```
Package                   Version
------------------------- ------------------
absl-py                   2.1.0
accelerate                1.1.1
addict                    2.4.0
aiohappyeyeballs          2.4.3
aiohttp                   3.10.10
aiosignal                 1.3.1
albucore                  0.0.16
albumentations            1.4.15
annotated-types           0.7.0
ansi2html                 1.9.2
antlr4-python3-runtime    4.9.3
anyio                     4.6.2.post1
argcomplete               3.5.1
arrow                     1.3.0
attrs                     24.2.0
beautifulsoup4            4.12.3
binaryornot               0.4.4
bitsandbytes              0.45.1.dev0
black                     24.10.0
boto3                     1.34.86
botocore                  1.34.162
cachetools                5.5.0
certifi                   2024.8.30
cffi                      1.17.1
chardet                   5.2.0
charset-normalizer        3.4.0
click                     8.1.7
cmake                     3.30.5
color-matcher             0.5.0
colorama                  0.4.6
coloredlogs               15.0.1
colorlog                  6.9.0
colour-science            0.4.6
ComfyUI-EasyNodes         1.2.7
contourpy                 1.3.0
cookiecutter              2.6.0
cryptography              43.0.3
cssselect2                0.7.0
cstr                      0.1.0
cupy-cuda12x              13.3.0
cycler                    0.12.1
Cython                    3.0.11
datamodel-code-generator  0.26.2
ddt                       1.7.2
deepdiff                  8.0.1
Deprecated                1.2.14
diffusers                 0.31.0
dill                      0.3.9
distro                    1.9.0
dnspython                 2.7.0
docutils                  0.21.2
easydict                  1.13
einops                    0.8.0
email_validator           2.2.0
eval_type_backport        0.2.0
facexlib                  0.3.0
fairscale                 0.4.13
fastapi                   0.115.4
fastrlock                 0.8.2
ffmpy                     0.3.0
filelock                  3.16.1
filterpy                  1.4.5
flatbuffers               24.3.25
flet                      0.24.1
flet-core                 0.24.1
flet-runtime              0.24.1
fonttools                 4.54.1
frozenlist                1.4.1
fsspec                    2024.10.0
ftfy                      6.3.1
fvcore                    0.1.5.post20221221
gdown                     5.2.0
genson                    1.3.0
gguf                      0.10.0
gitdb                     4.0.11
GitPython                 3.1.43
h11                       0.14.0
httpcore                  1.0.6
httptools                 0.6.4
httpx                     0.27.2
huggingface-hub           0.25.2
humanfriendly             10.0
idna                      3.10
imageio                   2.36.0
imageio-ffmpeg            0.5.1
img2texture               1.0.6
importlib_metadata        8.5.0
inflect                   5.6.2
insightface               0.7.3
iopath                    0.1.10
isort                     5.13.2
jax                       0.4.35
jaxlib                    0.4.35
Jinja2                    3.1.4
jiter                     0.7.1
jmespath                  1.0.1
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
kiwisolver                1.4.7
kornia                    0.7.3
kornia_rs                 0.1.5
lark                      1.2.2
lazy_loader               0.4
llvmlite                  0.43.0
loguru                    0.7.2
ltx-video                 0.1.0
lxml                      5.3.0
manifold3d                2.5.1
mapbox_earcut             1.0.2
markdown-it-py            3.0.0
MarkupSafe                3.0.2
matplotlib                3.9.2
matrix-client             0.4.0
mdurl                     0.1.2
mediapipe                 0.10.18
ml_dtypes                 0.5.0
mpmath                    1.3.0
mss                       9.0.2
multidict                 6.1.0
mypy-extensions           1.0.0
networkx                  3.4.2
ninja                     1.11.1.2
numba                     0.60.0
numpy                     1.26.4
nvidia-cuda-runtime-cu12  12.6.77
oauthlib                  3.2.2
omegaconf                 2.3.0
onnx                      1.17.0
onnxruntime-gpu           1.20.1
openai                    1.55.0
opencv-contrib-python     4.10.0.84
opencv-python             4.10.0.84
opencv-python-headless    4.10.0.84
opt_einsum                3.4.0
orderly-set               5.2.2
packaging                 23.2
pandas                    2.2.3
pathspec                  0.12.1
peft                      0.13.2
piexif                    1.1.3
pilgram                   1.2.1
pillow                    11.0.0
pip                       24.3.1
pixeloe                   0.0.10
platformdirs              4.3.6
pooch                     1.8.2
portalocker               2.10.1
prettytable               3.12.0
propcache                 0.2.0
protobuf                  4.25.5
psutil                    6.1.0
py-cpuinfo                9.0.0
pycollada                 0.8
pycparser                 2.22
pydantic                  2.9.2
pydantic_core             2.23.4
pygit2                    1.16.0
PyGithub                  2.4.0
Pygments                  2.18.0
PyJWT                     2.9.0
PyMatting                 1.1.12
PyNaCl                    1.5.0
pynvml                    11.5.3
pyparsing                 3.2.0
pypng                     0.20220715.0
pyreadline3               3.5.4
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-slugify            8.0.4
pytz                      2024.2
pywin32                   308
PyYAML                    6.0.2
qrcode                    7.4.2
referencing               0.35.1
regex                     2024.9.11
rembg                     2.0.60
repath                    0.9.0
reportlab                 4.2.5
requests                  2.32.3
rich                      13.9.4
rpds-py                   0.20.1
Rtree                     1.3.0
s3transfer                0.10.3
safetensors               0.4.5
sageattention             2.0.0
sageattention             2.0.0
scikit-image              0.24.0
scikit-learn              1.5.2
scipy                     1.14.1
seaborn                   0.13.2
segment-anything          1.0
sentencepiece             0.1.99
setuptools                75.6.0
shapely                   2.0.6
shellingham               1.5.4
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
sounddevice               0.5.1
soundfile                 0.12.1
soupsieve                 2.6
spandrel                  0.4.0
starlette                 0.41.2
surrealist                1.0.3
svg.path                  6.3
svglib                    1.5.1
sympy                     1.13.1
tabulate                  0.9.0
tensorrt_cu12             10.7.0
tensorrt_cu12_bindings    10.7.0
tensorrt_cu12_libs        10.7.0
termcolor                 2.5.0
text-unidecode            1.3
threadpoolctl             3.5.0
tifffile                  2024.9.20
timm                      1.0.11
tinycss2                  1.4.0
tokenizers                0.19.1
tomli                     2.1.0
torch                     2.5.1+cu124
torchaudio                2.5.1+cu124
torchsde                  0.2.6
torchvision               0.20.1+cu124
tqdm                      4.66.5
trampoline                0.1.2
transformers              4.44.2
transparent-background    1.3.3
trimesh                   4.5.2
triton                    3.1.0
typer                     0.12.5
types-python-dateutil     2.9.0.20241003
typing_extensions         4.12.2
tzdata                    2024.2
ultralytics               8.3.27
ultralytics-thop          2.0.10
urllib3                   1.26.20
uvicorn                   0.32.0
vhacdx                    0.0.8.post1
watchdog                  4.0.2
watchfiles                0.24.0
wcwidth                   0.2.13
webcolors                 24.8.0
webencodings              0.5.1
websocket-client          1.8.0
websockets                13.1
wget                      3.2
win32-setctime            1.1.0
wrapt                     1.16.0
xatlas                    0.0.9
xxhash                    3.5.0
yacs                      0.1.8
yapf                      0.40.2
yarl                      1.15.5
zipp                      3.20.2
```

**Comment by kijai** [comment]
transformers perhaps? I'm on latest with that

**Comment by Ratinod** [comment]
> transformers perhaps? I'm on latest with that

↑↑↑↑↑
THIS.


```
python_embeded\python.exe -m pip install accelerate==1.2.0
python_embeded\python.exe -m pip install transformers==4.47.0
```
now works with 1.2.0 :)

@RuslanKuz  you can check it too

**Comment by RuslanKuz** [comment]
> > transformers perhaps? I'm on latest with that
> 
> ↑↑↑↑↑ THIS.
> 
> ```
> python_embeded\python.exe -m pip install accelerate==1.2.0
> python_embeded\python.exe -m pip install transformers==4.47.0
> ```
> 
> now works with 1.2.0 :)
> 
> @RuslanKuz you can check it too

Yes, it works well! Thanks again!
