### ISSUE TITLE
no way to make and image. always black render...

### ISSUE THREAD

**Issue by francaleu** [kijai/ComfyUI-HunyuanVideoWrapper#118]
I've installed it 3 times , loading all different models..etc and always a blacj render. I don't understand what Is not working because there is no apparent error.

**Comment by 4lt3r3go** [comment]
try all bf16
![image](https://github.com/user-attachments/assets/85b1f3f7-a2ad-4038-98ee-808c59e89f2e)

**Comment by francaleu** [comment]
using the same settings.. black screen.

**Comment by kijai** [comment]
Need pytorch version 2.5.1 to use sdpa, it's an integral piece of everything in Comfy so I do not want to force the version automatically (as no one but comfy should). However latest comfy comes with that version and it's very stable, so highly recommend updating to that in general as well.

**Comment by francaleu** [comment]
thanks Kijai . going to it

**Comment by francaleu** [comment]
working great now !! a fresh install of comfyui and everything great
thank you again

**Comment by miguel-shaokahn** [comment]
I've installed pytorch 251 and changed all the precision to bf16 but still not working.. there is a away to check the resources ?

**Comment by miguel-shaokahn** [comment]
Fixed guys, I had to run also update_comfyui_and_python_dependencies.bat

**Comment by sl33pyC01E** [comment]
this is now completely broken for me. Updating makes it worse. Downgrading makes it worse.
