### ISSUE TITLE
where to connect negative prompt now?

### ISSUE THREAD

**Issue by 4lt3r3go** [kijai/ComfyUI-HunyuanVideoWrapper#12]
it was working fine before, now broken 
![image](https://github.com/user-attachments/assets/cda563fe-6f30-4c8e-a1ae-fc46115417c2)

**Comment by 4lt3r3go** [comment]
its fine. updated again and restartd.

Only i dont get were i have to put negative prompt now

**Comment by 4lt3r3go** [comment]
i updated and managed to make it work again by connecting only positive.
i guess negative is not necessary anymore?

**Comment by kijai** [comment]
> i updated and managed to make it work again by connecting only positive. i guess negative is not necessary anymore?

Yeah I got confused by the code initially as it has code for both undistilled and distilled models, the one they released is cfg distilled which means it should be ran with cfg 1.0, which also then can't use negative prompts. The positive is that this makes the model twice as fast.

**Comment by kijai** [comment]
Unless/until they release the undistilled model, there won't be negative prompting, so I'll close this.

**Comment by 4lt3r3go** [comment]
thanks for all your work Sir. 🤍🙏🏻
