### ISSUE TITLE
Is a 4070 Super enough? Slow Generation times for me

### ISSUE THREAD

**Issue by Heetoprime** [kijai/ComfyUI-HunyuanVideoWrapper#124]
I'm generating on a 4070 Super and it's pretty slow, takes about 10 minutes for 9 frames @ 240x160. I have sageattention and triton installed.

Is it my GPU or a setting/installation I'm missing? Thanks.

EDIT: Ok I didn't realize I had to use bf16 for the model, that reduced it to 5 minutes, but more tips would be appreciated.
EDIT2: Blockswap node cut down times to about 1-2 minutes!

**Comment by sd2530615** [comment]
you might stucked in decoding part ,uncheck the auto tile size and lower the spatial tile sample min size to 128 might helpful

**Comment by agustincaniglia** [comment]
did you see this?
https://www.reddit.com/r/StableDiffusion/comments/1h7hunp/how_to_run_hunyuanvideo_on_a_single_24gb_vram_card/

**Comment by Kvento** [comment]
> EDIT2: Blockswap node cut down times to about 1-2 minutes!

What parameters did you use for Blockswap?

**Comment by Heetoprime** [comment]
> did you see this? https://www.reddit.com/r/StableDiffusion/comments/1h7hunp/how_to_run_hunyuanvideo_on_a_single_24gb_vram_card/

Yes, I followed this guide actually. It's helpful but blockswap was the main reason my times went down

> > EDIT2: Blockswap node cut down times to about 1-2 minutes!
> 
> What parameters did you use for Blockswap?

I'm at work but I think I used "20" for the first parameter and "0" for the second. Important part is to link your blockswap node properly to the model node.

**Comment by agustincaniglia** [comment]
@Heetoprime so blockswap node can also be applied to t2v? also do you need a 4000 RTX series? I have the 3090.

**Comment by kijai** [comment]
If block swap reduces the sampling time, that means it fits in your memory with it. Otherwise block swapping slows the sampling, as it has to move the blocks between CPU and GPU. The idea is to find the minimum amount of blocks needed to swap for your available VRAM. Double blocks (as the name alludes) are twice as big as single blocks.

**Comment by Kvento** [comment]
> I'm at work but I think I used "20" for the first parameter and "0" for the second. Important part is to link your blockswap node properly to the model node.

Thanks for the reply! Could you please attach a screenshot of the blockswap node when you get a chance?

**Comment by agustincaniglia** [comment]
Wouw I reduced my VRAM a lot by this node and I just generated a 1344x768x73f video. Besides the quality is so good I can not even be jelous of Sora. This is beyond amazing!

**Comment by Kvento** [comment]
> Besides the quality is so good I can not even be jelous of Sora. This is beyond amazing!

Agree! And this is completely uncensored and so now I can make ~~explicit~~ any content with this model :)

**Comment by Heetoprime** [comment]
> I was able to run this model on a 2080ti (11gb VRAM)! 400x224 with 49f is the best I could get. To do this, I had to turn the Blockswap settings to the maximum (I have no idea whether this affects the quality or not). Unfortunately SageAttention is not available for this GPU so I used Sdpa.
> 
> ![2024-12-13_03-34-46](https://private-user-images.githubusercontent.com/15001752/395372269-7d562470-b757-4dd1-a155-8b8804be9e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTM3NTIsIm5iZiI6MTczNDA1MzQ1MiwicGF0aCI6Ii8xNTAwMTc1Mi8zOTUzNzIyNjktN2Q1NjI0NzAtYjc1Ny00ZGQxLWExNTUtOGI4ODA0YmU5ZTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDAxMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYzE4ZDdkZDI1MjE1OWNjYzJlMWU1MjhlZDc2ZWYyZGM1Njk5NjJkODZmN2ZiNzExYTY2MjVjNjlkNzVjZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q4rN9iVCP2vWDU5CkG4OZyuvVp0OGLDxVILnYAaogaY)

Nice! Here's my setup too:
![image](https://github.com/user-attachments/assets/2c6b2df0-6f1b-4708-8d09-d70a5618f071)

But Sageattention speeds things up considerably, I'd recommend installing it if you get a newer GPU.

**Comment by kijai** [comment]
> I was able to run this model on a 2080ti (11gb VRAM)! 400x224 with 49f is the best I could get. To do this, I had to turn the Blockswap settings to the maximum (I have no idea whether this affects the quality or not). Unfortunately SageAttention is not available for this GPU so I used Sdpa.
> 
> ![2024-12-13_03-34-46](https://private-user-images.githubusercontent.com/15001752/395372269-7d562470-b757-4dd1-a155-8b8804be9e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzI3MTAsIm5iZiI6MTczNDA3MjQxMCwicGF0aCI6Ii8xNTAwMTc1Mi8zOTUzNzIyNjktN2Q1NjI0NzAtYjc1Ny00ZGQxLWExNTUtOGI4ODA0YmU5ZTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA2NDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYzRiYmQ0MDRlMmE5N2Y4NjhiZmE2MzA0MzA0NTE3ZmE2MTE0OGQyZTFhYWZlYjlkMTk3OTM0OWU5N2E3OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.39viANYTisK76TH3TkKgalnjXtJ1SPwCwwdn7suTO7g)

Block swapping does not affect quality, but the resolution definitely does, not only image quality but motion too. You can further offload the txt_ing and img_in layers with the block swap node, that saves about ~500-700MB if I remember correctly, but further slows things down a bit.
