### ISSUE TITLE
Any chance of Img2Vid happening?

### ISSUE THREAD

**Issue by Heetoprime** [kijai/ComfyUI-HunyuanVideoWrapper#132]
Since CogVideoXWrapper has img2vid I'm wondering if this wrapper will get it too?

**Comment by CambridgeComputing** [comment]
> Since CogVideoXWrapper has img2vid I'm wondering if this wrapper will get it too?

This is dependent on the model itself. The creators of HunyuanVideo said that they are planning a model that supports i2v sometime in the next quarter, so we'd most likely need to wait until then to see it implemented here.

**Comment by Ratinod** [comment]
a roadmap: https://github.com/Tencent/HunyuanVideo?tab=readme-ov-file#-open-source-plan

**Comment by Heetoprime** [comment]
Ty guys, very helpful.
