### ISSUE TITLE
Request: add image injection node into hunyuan rfinverion

### ISSUE THREAD

**Issue by Reginald-L** [kijai/ComfyUI-HunyuanVideoWrapper#134]
great work!

would you plan to add the image injection node into hunyuan rf-inversion, that should be like this image
![image](https://github.com/user-attachments/assets/25e5cbb4-1f14-466b-bcd4-fe15747b51b9)

**Comment by kijai** [comment]
It would not work because this model doesn't have image2video capability.

**Comment by GJohGJ** [comment]
I think its planned so little more patient. Roadmap on github I think
