### ISSUE TITLE
Black output

### ISSUE THREAD

**Issue by popovidis** [kijai/ComfyUI-HunyuanVideoWrapper#137]
Hi there, I am using the example vid2vid workflow. I changed nothing but change the output framerate to 12 in the video combine and changed the video input from upload to path (since I have the video on the machine already). Otherwise everything is exactly like it was when I imported the workflow. Any idea what I am doing wrong?

![image](https://github.com/user-attachments/assets/90c75d03-28ab-4ea9-b76c-59552cc42e50)

**Comment by kijai** [comment]
So far I've only seen two reason for this: torch version prior to 2.5.1 and using fp16 as model dtype, which in latest updates I've decided to not even allow anymore as I've not seen it work for anyone.

**Comment by popovidis** [comment]
> So far I've only seen two reason for this: torch version prior to 2.5.1 and using fp16 as model dtype, which in latest updates I've decided to not even allow anymore as I've not seen it work for anyone.

This machine is running the default workflow with `2.4.0+cu121` torch.

[test.json](https://github.com/user-attachments/files/18126329/test.json)

No errors.

**Comment by kijai** [comment]
I should've clarified, the torch version is an issue when using sdpa attention, otherwise probably not.

**Comment by popovidis** [comment]
Without sdpa it goes OOM (48gb vram + 50gb ram)

![image](https://github.com/user-attachments/assets/9df0b02a-f570-420d-ba35-30c8159ec3e1)

**Comment by popovidis** [comment]
updating torch worked

**Comment by kijai** [comment]
> > I should've clarified, the torch version is an issue when using sdpa attention, otherwise probably not.
> 
> ![image](https://private-user-images.githubusercontent.com/120704725/395564069-6357b597-7b9d-4ba7-8b7d-295d89544f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTgyMDEsIm5iZiI6MTczNDA5NzkwMSwicGF0aCI6Ii8xMjA3MDQ3MjUvMzk1NTY0MDY5LTYzNTdiNTk3LTdiOWQtNGJhNy04YjdkLTI5NWQ4OTU0NGY3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxMzUxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmNhZjRkYTg0MDA1MjNmZDRhMzQyZjI1YTBiZTc3OWFlMzU0YTAwNWExODUzNmEzYTc0Yzk4ZDc5NmY5OTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fCrF0VALyCKw9Qvrt_huF_yUMHj-SqnXnUVDNvXh8OY)
> 
> sdpa is the attention mode in the example vid2vid.
> 
> So either don't use sdpa or update torch?

It's the default because most users use Windows and installing flash_attention or sageattention requires lots of extra steps, it's still the worst of the options otherwise.

**Comment by popovidis** [comment]
> > > I should've clarified, the torch version is an issue when using sdpa attention, otherwise probably not.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/120704725/395564069-6357b597-7b9d-4ba7-8b7d-295d89544f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTgyMDEsIm5iZiI6MTczNDA5NzkwMSwicGF0aCI6Ii8xMjA3MDQ3MjUvMzk1NTY0MDY5LTYzNTdiNTk3LTdiOWQtNGJhNy04YjdkLTI5NWQ4OTU0NGY3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxMzUxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmNhZjRkYTg0MDA1MjNmZDRhMzQyZjI1YTBiZTc3OWFlMzU0YTAwNWExODUzNmEzYTc0Yzk4ZDc5NmY5OTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fCrF0VALyCKw9Qvrt_huF_yUMHj-SqnXnUVDNvXh8OY)
> > sdpa is the attention mode in the example vid2vid.
> > So either don't use sdpa or update torch?
> 
> It's the default because most users use Windows and installing flash_attention or sageattention requires lots of extra steps, it's still the worst of the options otherwise.

the other options did not work sadly out of the box, just needed to test the workflow so I can try the lora training. Any way to use controlnet with this btw?
