### ISSUE TITLE
Load models straight to VRAM, bypass system RAM

### ISSUE THREAD

**Issue by CambridgeComputing** [kijai/ComfyUI-HunyuanVideoWrapper#139]
I don't have any experience development-wise with diffusion models and am not great with Python (yet!), but I was trying to go through the ComfyUI code as well as yours to try and figure out if there is a way to have models loaded directly to VRAM. I have 48GB VRAM but only 32GB of system RAM for now. When I try to run a workflow, it takes 10+ minutes to get going since it consumes all system RAM and tons of swap space/paging file, before finally moving to VRAM. Do you know if it's possible to skip the system RAM and go straight to VRAM, or is that just not possible? I'm willing to do the work to get something like this implemented, I just need a pointer in the right direction or confirmation that it's just not possible. Thanks!

**Comment by kijai** [comment]
Many of the nodes have the offloading as option, you an just disable the "force_offload" and it stays on VRAM, further you can launch comfy with --highvram which makes the "offload_device" into your GPU instead of CPU, so everything should stay on VRAM.

**Comment by CambridgeComputing** [comment]
> Many of the nodes have the offloading as option, you can just disable the "force_offload" and it stays on VRAM, further you can launch comfy with --highvram which makes the "offload_device" into your GPU instead of CPU, so everything should stay on VRAM.

Thanks for the quick response! I'll give that a shot and report back in case anyone else is wondering the same thing.

**Comment by CambridgeComputing** [comment]
I can confirm that this worked! I added `--highvram` to my ComfyUI launch args and it started loading into VRAM right away. Still took _most_ of my system RAM, but I can work around that. Thanks again for the tip!
