### ISSUE TITLE
blank video every time

### ISSUE THREAD

**Issue by mostafablender** [kijai/ComfyUI-HunyuanVideoWrapper#141]
Hi  i have rtx4060 with 16 VRAM   i run it on 20 steps and 49 freams i ran all of the json examples and still no video . i take a lot of time to render but give me only blank video

**Comment by Wabisabi591** [comment]
Solution here [118](https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/issues/118)

**Comment by mostafablender** [comment]
> Solution here [118](https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/issues/118)

thank you it solved .
i had to update my torch 
  do you know any way that i can use this model to do an image to video ?

**Comment by kijai** [comment]
Image2video will not be properly possible before they release that version of the model, initially they have said it would be around first quarter of 2025.
