### ISSUE TITLE
HunyuanVideo CFG node does not work with clip_l

### ISSUE THREAD

**Issue by Djanghost** [kijai/ComfyUI-HunyuanVideoWrapper#145]
Get an error when trying to use the “HunyuanVideo CFG” node alongside clip_l : "expected Tensor as element 0 in argument 0, but got NoneType"

![CFG-CLIP_l-ERROR](https://github.com/user-attachments/assets/aa582532-cbab-478b-a865-c04e57d58488)

**Comment by kijai** [comment]
I hadn't added negative prompt encoding for that case, should work now.
