### ISSUE TITLE
Difference in output quality/prompt following with the official inference code.

### ISSUE THREAD

**Issue by ghost** [kijai/ComfyUI-HunyuanVideoWrapper#15]
Using this prompt for example `Vocaloid Hatsune Miku skateboarding in New York.`, the original code does a good job at including someone that resembles Miku, while the results with this node seem more random. Both are using the FP8 model because I patched the original code with this: https://files.catbox.moe/1oxldo.diff

![test](https://github.com/user-attachments/assets/fe03b623-c6b3-4fa4-8506-236344182c88)

Here's one example video with the original code:

https://github.com/user-attachments/assets/422c2116-ab19-47c0-83a4-8d535aeadd8a

It was created with this command:

``` bash
python3 sample_video.py \
    --video-size 960 544 \
    --video-length 33 \
    --infer-steps 50 \
    --prompt "Vocaloid Hatsune Miku skateboarding in New York." \
    --flow-reverse \
    --use-cpu-offload \
    --save-path ./results --seed 1008437192147815
```

And this was with this node and the same settings:

https://github.com/user-attachments/assets/19b6e601-38ce-41ab-9335-bf996ac6c78a

Here's the ComfyUI workflow:
https://files.catbox.moe/t514kd.mp4

**Comment by kijai** [comment]
Yep, fixed, mistake in text encoder settings.
