### ISSUE TITLE
TorchCompile wont work

### ISSUE THREAD

**Issue by zeldapkmn** [kijai/ComfyUI-HunyuanVideoWrapper#154]
"torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\Users\vvv\AppData\Local\Temp\torchinductor_vvv\cache\.15364.8272.tmp' -> 'C:\Users\vvv\AppData\Local\Temp\torchinductor_vvv\cache\e9c66999a79b83be5e0f645f1fd6b11d91e4f8d057576d48cdcf8757f0e2cfc7'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
import torch._dynamo
torch._dynamo.config.suppress_errors = True"

Keep getting this error, only running with dynamic mode enabled works. Also, this is the only mode that lets me render 1280 x 720 at 65 frames, 30 steps, denoise 1, flow shift 12.

Why? Have 4090 24GB 32GB RAM 7800X3D

**Comment by perobueno** [comment]
Have you installed triton...? Have you read the install instructions for that? I saw them on reddit.

**Comment by zeldapkmn** [comment]
> Have you installed triton...? Have you read the install instructions for that? I saw them on reddit.

I have, using this guide: https://www.reddit.com/r/StableDiffusion/comments/1h7hunp/how_to_run_hunyuanvideo_on_a_single_24gb_vram_card/

Also, compiling with dynamic=true works, but I feel that defeats the point of using pytorch to speed up compiling

**Comment by selectai255** [comment]
> > Have you installed triton...? Have you read the install instructions for that? I saw them on reddit.
> 
> I have, using this guide: https://www.reddit.com/r/StableDiffusion/comments/1h7hunp/how_to_run_hunyuanvideo_on_a_single_24gb_vram_card/
> 
> Also, compiling with dynamic=true works, but I feel that defeats the point of using pytorch to speed up compiling



i found this earlier , could be related to your problem

"There was one caveat - Torch has a bug on Windows that causes a failure when overwriting a temp file. To fix that, I found a patch here: https://github.com/pytorch/pytorch/pull/138331/files

The line numbers in the patch do not match the current stable code that Comfy UI uses, but I found the relevant fragment at line 466 and replaced it with

try:

tmp_path.rename(target=path)

except FileExistsError as e_file_exist:

if not _IS_WINDOWS:

raise

# On Windows file exist is expected: https://docs.python.org/3/library/pathlib.html#pathlib.Path.rename

# Below two lines code is equal to \tmp_path.rename(path)` on non-Windows OS.`

# 1. Copy tmp_file to Target(Dst) file.

shutil.copy2(src=tmp_path, dst=path)

# 2. Delete tmp_file.

os.remove(tmp_path)

and now it works OK."

**Comment by zeldapkmn** [comment]
> > > Have you installed triton...? Have you read the install instructions for that? I saw them on reddit.
> > 
> > 
> > I have, using this guide: https://www.reddit.com/r/StableDiffusion/comments/1h7hunp/how_to_run_hunyuanvideo_on_a_single_24gb_vram_card/
> > Also, compiling with dynamic=true works, but I feel that defeats the point of using pytorch to speed up compiling
> 
> i found this earlier , could be related to your problem
> 
> "There was one caveat - Torch has a bug on Windows that causes a failure when overwriting a temp file. To fix that, I found a patch here: https://github.com/pytorch/pytorch/pull/138331/files
> 
> The line numbers in the patch do not match the current stable code that Comfy UI uses, but I found the relevant fragment at line 466 and replaced it with
> 
> try:
> 
> tmp_path.rename(target=path)
> 
> except FileExistsError as e_file_exist:
> 
> if not _IS_WINDOWS:
> 
> raise
> 
> # On Windows file exist is expected: https://docs.python.org/3/library/pathlib.html#pathlib.Path.rename
> # Below two lines code is equal to \tmp_path.rename(path)` on non-Windows OS.`
> # 1. Copy tmp_file to Target(Dst) file.
> shutil.copy2(src=tmp_path, dst=path)
> 
> # 2. Delete tmp_file.
> os.remove(tmp_path)
> 
> and now it works OK."

Yup saw this comment earlier today now it works like a charm
