### ISSUE TITLE
Where is lm_type?

### ISSUE THREAD

**Issue by RaySteve312** [kijai/ComfyUI-HunyuanVideoWrapper#156]
according to the introduction, there should be an option to be set as  vision_language. 
![屏幕截图 2024-12-17 195539](https://github.com/user-attachments/assets/de37ec82-3020-44d7-87e3-e4f20f85eb6a)

**Comment by kijai** [comment]
That part of the readme should be updated, it's autodetected now.

**Comment by RaySteve312** [comment]
thanks!
