### ISSUE TITLE
LoRAs appear to not be working with the new FP8 model by Hunyuan Video

### ISSUE THREAD

**Issue by Bobothesecond** [kijai/ComfyUI-HunyuanVideoWrapper#164]
I'm not sure if this is expected behavior or not, but it seems that LoRAs trained on the previous FP8 model do not apply to the FP8 model by Hunyuan.

I generated two very short videos to test the LoRA's effect on the output.

FP8 by Hunyuan:

https://github.com/user-attachments/assets/7027c987-3ff9-45f8-8c0c-6d60219a7325

FP8 by Kijai:

https://github.com/user-attachments/assets/1781ee51-0642-4118-94f0-8ecee658371b

As you can see, the model by Kijai successfully applied the LoRA and looks like the subject.
I'm not sure if this is something that can be remedied as the models might be quite different internally, but just thought I should report the behavior.

**Comment by kijai** [comment]
Yeah it doesn't work with the scaling method, not sure how to work around that yet.

**Comment by Bobothesecond** [comment]
I figured as much. Well, we'll always have the original if there is no workaround.
