### ISSUE TITLE
Is there any difference from hunyuan-video-t2v-720p/transformers to Kijai/HunyuanVideo_comfy？

### ISSUE THREAD

**Issue by a-cold-bird** [kijai/ComfyUI-HunyuanVideoWrapper#165]

**Comment by Kvento** [comment]
I didn't notice any difference in the generation result. However, the official model can be launched with base precision fp32 which can be useful for older cards that don't support bf16.
#160

**Comment by kijai** [comment]
With the bf16 weight there's no difference, with the fp8 there's big difference, they have done more advanced quantization which is better, but currently isn't supported by all of the code, it works but for example LoRAs with it do not.
