### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by wstcok2003** [kijai/ComfyUI-HunyuanVideoWrapper#167]
In window system
pytorch version: 2.5.1+cu121
xformers version: 0.0.28.post3

When I finished installing, restart comfyui
Display error (IMPORT FAILED): C:\Users\admin\Desktop\AI\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapp

I tried fixing it, but the above error shows up every time I start it.

I updated comfyui to the latest version and still got the above error.

Please tell me how to solve it. Has anyone else encountered similar problems? How to solve it?

**Comment by selectai255** [comment]
there should be more information about the error on the console before you get to the list of custom nodes importing , post that info , easier to help

**Comment by wstcok2003** [comment]
I deleted the original comfyUI directory and re-downloaded the latest version, and it worked. It is probably a problem when updating Comfyui.
