### ISSUE TITLE
redundant llava_lama copies

### ISSUE THREAD

**Issue by 4lt3r3go** [kijai/ComfyUI-HunyuanVideoWrapper#171]
There is some confusion regarding Llava_Lama .. i'm sorry its always me annoy i know 😁

When using your nodes, it is automatically downloaded and placed in the LLM folder 
`ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer`

However, comfy native nodes now asking to download one of this

![image](https://github.com/user-attachments/assets/180b910c-322f-4d30-b057-0ad1558e9d9c)

which are placed in a different folder: `ComfyUI/models/text_encoders`
 

As a result, many users end up with a sort of duplicate (or am I wrong?).

Is there a way to avoid this? 
The files are quite large, and having duplicates seems a bit redundant.

**Comment by kijai** [comment]
It's not only about the files, comfy has his own code to use them so they wouldn't be compatible anyway. Sure I could work on utilizing that, but at this point it feels like wasted effort as eventually people will move onto the native only anyway.

**Comment by 4lt3r3go** [comment]
i think your way has more sense tho. i'll stick on your nodes for now
admit that the ability to choose different samplers is inviting... uhm ok i'll give it a try

**Comment by Ratinod** [comment]
> people will move onto the native only anyway

This transition is very painful without sageattn, BlockSwap and Torch Compile...
