### ISSUE TITLE
Image Encode Error

### ISSUE THREAD

**Issue by eas125** [kijai/ComfyUI-HunyuanVideoWrapper#185]
This is an odd one. I get an error at TextImageEncode when an image is connected to Image 1. It works if connected to Image 2. Two images get the same error.

 File "N:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 214, in text2tokens
    raise ValueError("Only vision_languague models support image input")
ValueError: Only vision_languague models support image input

**Comment by kijai** [comment]
To use the image inputs you should use the full xtuner model.

**Comment by eas125** [comment]
That was it. I tried it earlier and was getting errors, so I assumed it was incorrect. Reloaded from git and downloaded the safetensors again. Worked. Something was wrong with the original download. 
Thanks for the reply. Helps concentrate on 1 thing to troubleshoot.

**Comment by ronbere** [comment]
> That was it. I tried it earlier and was getting errors, so I assumed it was incorrect. Reloaded from git and downloaded the safetensors again. Worked. Something was wrong with the original download. Thanks for the reply. Helps concentrate on 1 thing to troubleshoot.

Reloaded? can u help me?

**Comment by eas125** [comment]
> > That was it. I tried it earlier and was getting errors, so I assumed it was incorrect. Reloaded from git and downloaded the safetensors again. Worked. Something was wrong with the original download. Thanks for the reply. Helps concentrate on 1 thing to troubleshoot.
> 
> Reloaded? can u help me?

I just redownloaded the xtuner model and placed it in the models/LLM folder. If you're just doing t2v, use kijai's. If running the ip2v model use the full xtuner model.

![Image](https://github.com/user-attachments/assets/5dd2a6fe-0bab-4882-a39f-6040bca20a8a)
