### ISSUE TITLE
Problem with running the example

### ISSUE THREAD

**Issue by zetroxos** [kijai/ComfyUI-HunyuanVideoWrapper#190]
Hello, 
i've got a problem with running Hunyuan Video on ComfyUI
i've loaded 1 of your example workflows hyvideo_t2v_example_01.json and the video that is generating is all black

could you tell me what is wrong?

ps. our setup has 2x RTX 4090 (48GB Vram in total)

![2024-12-20_191635](https://github.com/user-attachments/assets/6029504a-ef40-4174-972e-0818724e7311)
![hyvideo_t2v_example_01 json](https://github.com/user-attachments/assets/969bdaa6-bba2-4730-9b52-a5256c535908)

https://github.com/user-attachments/assets/d973d7b4-87be-4305-bf09-53e77f56e5b4

**Comment by kijai** [comment]
To use sdpa attention mode, you need to have pytorch version 2.5.1 installed, or that happens.

**Comment by zetroxos** [comment]
that solved our problem, thank you

**Comment by dejian-lc** [comment]
Hello. Could you please tell me which attention modes are suitable for other versions of Torch? thank you，my torch version is 2.4.0

> To use sdpa attention mode, you need to have pytorch version 2.5.1 installed, or that happens.

**Comment by dejian-lc** [comment]
@kijai

**Comment by dejian-lc** [comment]
@kijai Because this torch version and hunyuanvideo's official installation requirements seem to be inconsistent, the official is 2.4.0

**Comment by kijai** [comment]
> @kijai Because this torch version and hunyuanvideo's official installation requirements seem to be inconsistent, the official is 2.4.0

The original used only flash attention.

**Comment by dejian-lc** [comment]
> > @kijai Because this torch version and hunyuanvideo's official installation requirements seem to be inconsistent, the official is 2.4.0
> 
> The original used only flash attention.

Thanks for your answer, I still used 2.5.1 at last. But I ran your example with fp8 model and got this result. I feel it is too different from your example, the bear's running track is inverted, is it because the original model was not used?


https://github.com/user-attachments/assets/9b78aa6d-d352-49c9-aebe-9a608172562c

**Comment by kijai** [comment]
> > > @kijai Because this torch version and hunyuanvideo's official installation requirements seem to be inconsistent, the official is 2.4.0
> > 
> > 
> > The original used only flash attention.
> 
> Thanks for your answer, I still used 2.5.1 at last. But I ran your example with fp8 model and got this result. I feel it is too different from your example, the bear's running track is inverted, is it because the original model was not used?
> HunhuyanVideo_00001.mp4

It's normal and can happen with just different seed, this method of video2video very loosely follows the input, you can reduce the denoise strength to force it to follow the input video closer.

**Comment by dejian-lc** [comment]
> > > > @kijai Because this torch version and hunyuanvideo's official installation requirements seem to be inconsistent, the official is 2.4.0
> > > 
> > > 
> > > The original used only flash attention.
> > 
> > 
> > Thanks for your answer, I still used 2.5.1 at last. But I ran your example with fp8 model and got this result. I feel it is too different from your example, the bear's running track is inverted, is it because the original model was not used?
> > HunhuyanVideo_00001.mp4
> 
> It's normal and can happen with just different seed, this method of video2video very loosely follows the input, you can reduce the denoise strength to force it to follow the input video closer.

Thank you. I actually used examples/hyvideo_v2v_example_01.json, and I didn't make any changes (including seed) except for the model using fp8. When you did this example, did you use your own quantified fp8 model or the official quantified model? In theory, I should be able to reproduce your results if the seed stays the same.

**Comment by kijai** [comment]
> > > > > @kijai Because this torch version and hunyuanvideo's official installation requirements seem to be inconsistent, the official is 2.4.0
> > > > 
> > > > 
> > > > The original used only flash attention.
> > > 
> > > 
> > > Thanks for your answer, I still used 2.5.1 at last. But I ran your example with fp8 model and got this result. I feel it is too different from your example, the bear's running track is inverted, is it because the original model was not used?
> > > HunhuyanVideo_00001.mp4
> > 
> > 
> > It's normal and can happen with just different seed, this method of video2video very loosely follows the input, you can reduce the denoise strength to force it to follow the input video closer.
> 
> Thank you. I actually used examples/hyvideo_v2v_example_01.json, and I didn't make any changes (including seed) except for the model using fp8. When you did this example, did you use your own quantified fp8 model or the official quantified model? In theory, I should be able to reproduce your results if the seed stays the same.

I used the first fp8 model I uploaded, not the official one. There's been many updates since that workflow was first made, it's possible some of that changes the output. Your output doesn't particularly look wrong to me, just different and very common thing to happen with high denoise.

**Comment by dejian-lc** [comment]
> > > > > > @kijai Because this torch version and hunyuanvideo's official installation requirements seem to be inconsistent, the official is 2.4.0
> > > > > 
> > > > > 
> > > > > The original used only flash attention.
> > > > 
> > > > 
> > > > Thanks for your answer, I still used 2.5.1 at last. But I ran your example with fp8 model and got this result. I feel it is too different from your example, the bear's running track is inverted, is it because the original model was not used?
> > > > HunhuyanVideo_00001.mp4
> > > 
> > > 
> > > It's normal and can happen with just different seed, this method of video2video very loosely follows the input, you can reduce the denoise strength to force it to follow the input video closer.
> > 
> > 
> > Thank you. I actually used examples/hyvideo_v2v_example_01.json, and I didn't make any changes (including seed) except for the model using fp8. When you did this example, did you use your own quantified fp8 model or the official quantified model? In theory, I should be able to reproduce your results if the seed stays the same.
> 
> I used the first fp8 model I uploaded, not the official one. There's been many updates since that workflow was first made, it's possible some of that changes the output. Your output doesn't particularly look wrong to me, just different and very common thing to happen with high denoise.

Ok, thank you very much for your answer, I will try again.
