### ISSUE TITLE
Invalid image type. Expected either PIL.Image

### ISSUE THREAD

**Issue by csad-dasc** [kijai/ComfyUI-HunyuanVideoWrapper#196]
This error message keeps showing up. Both Comfy and HunyuanVideoWrapper are updated to the latest version.

"Invalid image type. Expected either PIL.Image.Image, numpy.ndarray, torch.Tensor, tf.Tensor or jax.ndarray, but got <class 'str'>."

![err](https://github.com/user-attachments/assets/166703fd-7e52-4965-a3a9-620c39c865ac)

**Comment by Jamzsam** [comment]
Same here

**Comment by kijai** [comment]
I think it's some dependency version, probably transformers needing updating.
