### ISSUE TITLE
Adding comfyui attention mode

### ISSUE THREAD

**Issue by al3dv2** [kijai/ComfyUI-HunyuanVideoWrapper#2]
Hi flash_attn and sageattn doesn't works on my windows 10 (24go de vram ) I tried everything for install it without sucess can you add others attention mode like the comfyui one ? thanks !

**Comment by SUP3RMASS1VE** [comment]
same problem here.

**Comment by kijai** [comment]
The issue isn't adding them, they just don't work with the model, even the original code only works with flash_attn. Sdpa is already an option, but it didn't produce movement on my tests so far.

Both flash and sage can be installed on Windows, it's not super simple but very much possible. Sage is also a lot faster so it can be worth the effort, depending on your GPU.

**Comment by al3dv2** [comment]
Ok thanks for the answer do you know where there's a tutorial for install it on windows because pip install never works for both

**Comment by SUP3RMASS1VE** [comment]
> The issue isn't adding them, they just don't work with the model, even the original code only works with flash_attn. Sdpa is already an option, but it didn't produce movement on my tests so far.
> 
> Both flash and sage can be installed on Windows, it's not super simple but very much possible. Sage is also a lot faster so it can be worth the effort, depending on your GPU.

sdpa working for me but as you said no movement just pixelated movements

**Comment by kijai** [comment]
> Ok thanks for the answer do you know where there's a tutorial for install it on windows because pip install never works for both

It's more complicated than that, Purz made this guide a while ago that should still apply:

https://purz.notion.site/Get-Windows-Triton-working-for-Mochi-6a0c055e21c84cfba7f1dd628e624e97

**Comment by power88** [comment]
Here's a prebuilt triton package from this huggingface repo:
https://huggingface.co/madbuda/triton-windows-builds/tree/main
You can download one of them and install

**Comment by tarkansarim** [comment]
> > Ok thanks for the answer do you know where there's a tutorial for install it on windows because pip install never works for both
> 
> It's more complicated than that, Purz made this guide a while ago that should still apply:
> 
> https://purz.notion.site/Get-Windows-Triton-working-for-Mochi-6a0c055e21c84cfba7f1dd628e624e97

Did that and now getting this error. 
RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

**Comment by 4lt3r3go** [comment]
is weird cause after a lot of issues i had to figure to make Triton works for Mochi (and is actually working now)
but i can't run sage_att with the workflow shared here
`Can't import SageAttention: cannot import name 'sageattn_varlen' from 'sageattention' (F:\Comfy2\python_embeded\Lib\site-packages\sageattention\__init__.py)`

sdpa gives me pixelated results too

> Here's a prebuilt triton package from this huggingface repo: https://huggingface.co/madbuda/triton-windows-builds/tree/main You can download one of them and install

**Comment by WalkingwithAI** [comment]
> is weird cause after a lot of issues i had to figure to make Triton works for Mochi (and is actually working now) but i can't run sage_att with the workflow shared here `Can't import SageAttention: cannot import name 'sageattn_varlen' from 'sageattention' (F:\Comfy2\python_embeded\Lib\site-packages\sageattention\__init__.py)`
> 
> sdpa gives me pixelated results too
> 
> > Here's a prebuilt triton package from this huggingface repo: https://huggingface.co/madbuda/triton-windows-builds/tree/main You can download one of them and install

the same error msg.

**Comment by 4lt3r3go** [comment]
> Hi flash_attn and sageattn doesn't works on my windows 10 (24go de vram ) I tried everything for install it without sucess can you add others attention mode like the comfyui one ? thanks !

i would add at least the word "Sage" in the main title of this post cause expect more people entering with the same problem. 
at least we can converge everything in here

**Comment by kijai** [comment]
> is weird cause after i finally figured how to make Triton works for Mochi (wich is actually working now)
> i can't run sage_att with the workflow shared here
> 
> `Can't import SageAttention: cannot import name 'sageattn_varlen' from 'sageattention' (F:\Comfy2\python_embeded\Lib\site-packages\sageattention\__init__.py)`
> 
> sdpa gives me pixelated results too
> 
> > Here's a prebuilt triton package from this huggingface repo: https://huggingface.co/madbuda/triton-windows-builds/tree/main You can download one of them and install
> 
> 

The varlen version for sage was added later, so you probably need to update sageattention itself.

**Comment by 4lt3r3go** [comment]
> 
> sdpa working for me but as you said no movement just pixelated movements

i can confirm what Kijai sayd. Sdpa produce really subtle movements.
to avoid pixelation you need high steps. Got pixelation at 8 to 20 steps, at 32 steps pixelation almost disappeared.

**Comment by 4lt3r3go** [comment]
> The varlen version for sage was added later, so you probably need to update sageattention itself.

ok pasting here in case other users looking for same solution:
for comfy portable:
`F:\Your_Comfy_Directory\python_embeded\python.exe -m pip install --upgrade sageattention`

this solved. Now works. Thanks Kijai🤍

**Comment by knyeoh** [comment]
Is this pixilation? 

https://github.com/user-attachments/assets/05fb7dfd-71d7-4b53-8b3c-07ff0b3ebc15

**Comment by ghostorchidgaming** [comment]
> Did that and now getting this error. RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

If you are on Windows and using the Portable version of ComfyUI then there is a critical step explained on the **triton-windows** github under:
*Special notes if you're using ComfyUI with the embeded Python:*
https://github.com/woct0rdho/triton-windows

That was the last piece of the puzzle for me.

**Comment by kijai** [comment]
Might've finally figured it out, at least I can now use sdpa:

https://github.com/user-attachments/assets/adc14da4-7b0f-48d1-bbae-3a7250f9180c

**Comment by Smiden3** [comment]
> Возможно, я наконец-то понял это, по крайней мере, теперь я могу использовать sdpa:
> 
>  AnimateDiff_00002.63.mp4

как это стало возможно?
