### ISSUE TITLE
[Feature Request] Multi-GPU?

### ISSUE THREAD

**Issue by InconsolableCellist** [kijai/ComfyUI-HunyuanVideoWrapper#20]
Is it possible for this to take advantage of multiple GPUs? I have it working on my 3090! But generations are pretty slow and limited in resolution: ~5 minutes for 512x320

**Comment by kijai** [comment]
There is no parallel processing methods implemented in the original code yet, so that would be a no, also I don't have multiple GPUs to even work on that anyway. Best thing to improve speed is use torch.compile and sageattention.

**Comment by InconsolableCellist** [comment]
Interesting, I wasn't aware of torch.compile or sageattention. Do you know where I can learn more? Thanks

**Comment by kijai** [comment]
> Interesting, I wasn't aware of torch.compile or sageattention. Do you know where I can learn more? Thanks

Purz made a guide to get started on Windows:

https://purz.notion.site/Get-Windows-Triton-working-for-Mochi-6a0c055e21c84cfba7f1dd628e624e97

On Linux it's much simpler as Triton comes with torch

Sageattention is this and just an option in the model loader node to use it after everything is installed:

https://github.com/thu-ml/SageAttention

**Comment by InconsolableCellist** [comment]
Nice, I'm on Linux and looks like I'm already using `sagettn_varlen` in your `HunyuanVideo Model Loader` node

**Comment by kijai** [comment]
> Nice, I'm on Linux and looks like I'm already using `sagettn_varlen` in your `HunyuanVideo Model Loader` node

Okay, if that works then you should be able to connect the compile settings to the model loader as well, that enables the basic torch.compile. Compilation itself takes some time, but only on first run per input size. Torch 2.5.1 is heavily recommended for that too.

**Comment by AugmentedRealityCat** [comment]
Just wanted to say that I used the [Purz method posted by Kijai in this thread](https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/issues/20#issuecomment-2518783605) and it works well to install Triton and SageAttention on Windows 10.

```
Microsoft Windows [Version 10.0.19045.5131]
(c) Microsoft Corporation. All rights reserved.

D:\ComfyUI_windows_portable>python_embeded\python.exe --version
Python 3.12.7

D:\ComfyUI_windows_portable>python_embeded\python.exe -m pip install triton-3.1.0-cp312-cp312-win_amd64.whl
Processing d:\comfyui_windows_portable\triton-3.1.0-cp312-cp312-win_amd64.whl
Requirement already satisfied: filelock in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from triton==3.1.0) (3.16.1)
Installing collected packages: triton
Successfully installed triton-3.1.0

D:\ComfyUI_windows_portable>python_embeded\python.exe -m pip install sageattention
Collecting sageattention
  Downloading sageattention-1.0.6-py3-none-any.whl.metadata (5.6 kB)
Downloading sageattention-1.0.6-py3-none-any.whl (20 kB)
Installing collected packages: sageattention
Successfully installed sageattention-1.0.6

D:\ComfyUI_windows_portable>
```

**Comment by InconsolableCellist** [comment]
> > Nice, I'm on Linux and looks like I'm already using `sagettn_varlen` in your `HunyuanVideo Model Loader` node
> 
> Okay, if that works then you should be able to connect the compile settings to the model loader as well, that enables the basic torch.compile. Compilation itself takes some time, but only on first run per input size. Torch 2.5.1 is heavily recommended for that too.

For attaching the compiler settings, `HunyuanVideo Model Loader` wants a type of `compile_args`, but the screenshot in Purz' Windows guide shows only MochiWrappers and specifically a `Mochi Torch Compile Settings` node. What's the proper equivalent for the Hunyuan Video Model Loader? I updated just to check, but don't see a compatible input node that provides `compile_args`

**Comment by AugmentedRealityCat** [comment]
> What's the proper equivalent for the Hunyuan Video Model Loader?

Could it be this parameter, directly in the : 
![Screenshot 2024-12-04 at 23-01-07 hyvideo_v2v_example_01 - ComfyUI](https://github.com/user-attachments/assets/d13dd365-310c-4bdb-967c-262fcaee7a03)

When I ran the node for the first time, here is the compile log I got:

```
got prompt
The config attributes {'mid_block_causal_attn': True} were passed to AutoencoderKLCausal3D, but are not expected and will be ignored. Please verify your config.json configuration file.
encoded latents shape torch.Size([1, 16, 13, 48, 96])
Loading text encoder model (clipL) from: D:\ComfyUI_windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: D:\ComfyUI_windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
Loading text encoder model (llm) from: D:\ComfyUI_windows_portable\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.71s/it]
Text encoder to dtype: torch.float16
Loading tokenizer (llm) from: D:\ComfyUI_windows_portable\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
Using accelerate to load and assign model weights to device...
Scheduler config: FrozenDict({'num_train_timesteps': 1000, 'shift': 9.0, 'reverse': True, 'solver': 'euler', 'n_tokens': None, '_use_default_values': ['num_train_timesteps', 'n_tokens']})
Input (height, width, video_length) = (384, 768, 49)
tensor([1000.0000,  996.1832,  992.1259,  987.8048,  983.1933,  978.2609,  972.9730,  967.2897,  961.1651,  954.5454,  947.3684,  939.5604,  931.0344,  921.6867,  911.3924,  900.0000,  887.3240,  873.1343,  857.1429,  838.9830,  818.1818,  794.1176,  765.9575,  732.5581,  692.3077,  642.8571,  580.6452,  500.0001,
         391.3044,  236.8421], device='cuda:0')
Sampling 49 frames in 13 latents at 768x384 with 30 inference steps
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]main.c
   Creating library main.lib and object main.exp
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function 'quant_per_block_int8_kernel' for 'sm_89'
ptxas info    : Function properties for quant_per_block_int8_kernel
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 168 registers, 412 bytes cmem[0]
main.c
   Creating library main.lib and object main.exp
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function 'quant_per_block_int8_kernel' for 'sm_89'
ptxas info    : Function properties for quant_per_block_int8_kernel
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 412 bytes cmem[0]
ptxas info    : 11 bytes gmem, 8 bytes cmem[4]
ptxas info    : Compiling entry function '_attn_fwd' for 'sm_89'
ptxas info    : Function properties for _attn_fwd
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 246 registers, 464 bytes cmem[0]
main.c
   Creating library main.lib and object main.exp
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:38<00:00,  3.27s/it]
Allocated memory: memory=11.852 GB
Max allocated memory: max_memory=14.409 GB
Max reserved memory: max_reserved=14.906 GB
Prompt executed in 140.64 seconds
```

**Comment by AugmentedRealityCat** [comment]
There is a specific node for it called `HunyuanVideo Torch Compile Settings`

![Screenshot 2024-12-04 at 23-12-55 67% 60% HyVideoSampler](https://github.com/user-attachments/assets/581d63cd-2607-4fc7-a6b0-91ae7e8b6a68)

**Comment by InconsolableCellist** [comment]
Thanks. I updated again and this time saw the Compile Settings node.

Unfortunately I may be out of luck with my 3090, which has a compute compatibility of `8.6`. When I try to run the workflow with those compile settings I get:

```
Traceback (most recent call last):
  File "/home/user/micromamba/envs/comfyui/lib/python3.9/site-packages/triton/language/core.py", line 35, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/micromamba/envs/comfyui/lib/python3.9/site-packages/triton/language/core.py", line 993, in to
    return semantic.cast(self, dtype, _builder, fp_downcast_rounding)
  File "/home/user/micromamba/envs/comfyui/lib/python3.9/site-packages/triton/language/semantic.py", line 759, in cast
    assert builder.options.allow_fp8e4nv, "fp8e4nv data type is not supported on CUDA arch < 89"
AssertionError: fp8e4nv data type is not supported on CUDA arch < 89
```

A bit confusing, as the data type I have selected for the model loader is `fp8_e4m3fn`.

Are you using a 4090 or datacenter card with compute >= 89?

Here's my workflow:

![image](https://github.com/user-attachments/assets/d7033300-3889-4328-a716-5657b8ba0ac1)

Perhaps I'll have to rent time with a 4090 or better to try it with triton

**Comment by AugmentedRealityCat** [comment]
I do use a 4090 and I know that the special optimizations that make fp8_e4m3fn work faster is only for the 40xx generation of card - but I don't know what it means for different GPUs, as in are they running fp8_e4m3fn at all, or just running it slower ? As for datacenter-level GPUs, I have no idea as, sadly, I have mostly no experience with them.
