### ISSUE TITLE
How to get better result from LoRA?

### ISSUE THREAD

**Issue by popovidis** [kijai/ComfyUI-HunyuanVideoWrapper#202]
My loras look really weird. 

This is with my own lora:

![image](https://github.com/user-attachments/assets/7e531317-939e-448f-957b-42797cf10004)

This is with this lora: https://civitai.com/models/1029279/makima-hunyuan-character

<img width="787" alt="image" src="https://github.com/user-attachments/assets/6c900918-7b78-4a7e-b64f-96966877d801" />

What is wrong with my workflow which leads to the extremely unclear image.

Workflow:
[workflow_example (1).json](https://github.com/user-attachments/files/18223528/workflow_example.1.json)

**Comment by popovidis** [comment]
nothing changed with the workflow but updating the newest version of the repo fixed this

**Comment by Aristo23333** [comment]
Hi I use the https://github.com/tdrussell/diffusion-pipe to finetune the Hunyuan model on my own dataset and get a adapter_model.safetensors. But when I use this to inference I got a very vague video?
