### ISSUE TITLE
Install Missing Nodes redirect to SUPIR?

### ISSUE THREAD

**Issue by PGCRT** [kijai/ComfyUI-HunyuanVideoWrapper#21]
Hi, something maybe wrong on my end, but Missing Nodes windows redirect me to the wrong package 🔎👀

![2024-12-05 00_50_50-_hyvideo_t2v_example_01 (1) - ComfyUI](https://github.com/user-attachments/assets/6d1581ee-e397-48c6-92b0-0813e5482319)

**Comment by kijai** [comment]
Was probably caused by the nodes not being in the manager, somehow...
