### ISSUE TITLE
HyVideoTextImageEncode Invalid image type. Expected either PIL.Image.Image, numpy.ndarray, torch.Tensor, tf.Tensor or jax.ndarray, but got <class 'str'>.

### ISSUE THREAD

**Issue by gjnave** [kijai/ComfyUI-HunyuanVideoWrapper#223]
Everything was working yesteday and then today I got this.. ?? 
![image](https://github.com/user-attachments/assets/7c38d50b-90e7-4453-b18d-8c45b3f2721c)

**Comment by kijai** [comment]
Then something has downgraded your transformers -version, updating it should fix it.

**Comment by gjnave** [comment]
> Then something has downgraded your transformers -version, updating it should fix it.

alright must be a system pollution system. Thanks for the reply. I'll look into it and report back

**Comment by gjnave** [comment]
> > Then something has downgraded your transformers -version, updating it should fix it.
well there you go.. the transformers needed to be upgraded and I assume was sticking around in cache gumming up reinstalls.
 Curious, how did you know that was a transformers issue?

thx again

**Comment by gjnave** [comment]
well there you go.. the transformers needed to be upgraded and I assume was sticking around in cache gumming up reinstalls.
Curious, how did you know that was a transformers issue?

thx again
