### ISSUE TITLE
pls help me…

### ISSUE THREAD

**Issue by tiandaoyuxi** [kijai/ComfyUI-HunyuanVideoWrapper#24]
Using accelerate to load and assign model weights to device...
Scheduler config: FrozenDict([('num_train_timesteps', 1000), ('shift', 9.0), ('reverse', True), ('solver', 'euler'), ('n_tokens', None), ('_use_default_values', ['n_tokens', 'num_train_timesteps'])])
Input (height, width, video_length) = (320, 512, 69)
Sampling 69 frames in 18 latents at 512x320 with 30 inference steps
  0%|                                                                       | 0/30 [00:00<?, ?it/s]main.c
C:\Users\win11\AppData\Local\Temp\tmp1qwypcg6\main.c(12): fatal error C1083: 无法打开包括文件: “Python.h”: No such file or directory
  0%|                                                                       | 0/30 [00:01<?, ?it/s]
!!! Exception during processing !!! Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\Hostx64\\x64\\cl.EXE', 'C:\\Users\\win11\\AppData\\Local\\Temp\\tmp1qwypcg6\\main.c', '/nologo', '/O2', '/LD', '/wd4819', '/ID:\\Comfy_UI\\python_embeded\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '/IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\include', '/IC:\\Users\\win11\\AppData\\Local\\Temp\\tmp1qwypcg6', '/ID:\\Comfy_UI\\python_embeded\\Include', '/IC:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\include', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um', '/link', '/LIBPATH:D:\\Comfy_UI\\python_embeded\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '/LIBPATH:C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\lib\\x64', '/LIBPATH:D:\\Comfy_UI\\python_embeded\\libs', '/LIBPATH:D:\\Comfy_UI\\python_embeded\\libs', '/LIBPATH:D:\\Comfy_UI\\python_embeded\\libs', '/LIBPATH:C:\\Python311\\libs', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64', 'cuda.lib', '/OUT:C:\\Users\\win11\\AppData\\Local\\Temp\\tmp1qwypcg6\\cuda_utils.cp311-win_amd64.pyd']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "D:\Comfy_UI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Comfy_UI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 692, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 537, in __call__
    noise_pred = self.transformer(  # For an input image (129, 192, 336) (1, 256, 256)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 671, in forward
    img, txt = block(*double_block_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 203, in forward
    attn = attention(
           ^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\attention.py", line 126, in attention
    x = sageattn_varlen_func(
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\attention.py", line 24, in sageattn_varlen_func
    return sageattn_varlen(q, k, v, cu_seqlens_q, cu_seqlens_kv, max_seqlen_q, max_seqlen_kv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\sageattention\core.py", line 198, in sageattn_varlen
    q_int8, q_scale, k_int8, k_scale, cu_seqlens_q_scale, cu_seqlens_k_scale = per_block_int8_varlen(q, k, cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k, sm_scale=sm_scale)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\sageattention\quant_per_block_varlen.py", line 69, in per_block_int8
    quant_per_block_int8_kernel[grid](
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 607, in run
    device = driver.active.get_current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 9, in _create_driver
    return actives[0]()
           ^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 414, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 92, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 69, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\triton\runtime\build.py", line 71, in _build
    ret = subprocess.check_call(cc_cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\Hostx64\\x64\\cl.EXE', 'C:\\Users\\win11\\AppData\\Local\\Temp\\tmp1qwypcg6\\main.c', '/nologo', '/O2', '/LD', '/wd4819', '/ID:\\Comfy_UI\\python_embeded\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '/IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\include', '/IC:\\Users\\win11\\AppData\\Local\\Temp\\tmp1qwypcg6', '/ID:\\Comfy_UI\\python_embeded\\Include', '/IC:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\include', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um', '/link', '/LIBPATH:D:\\Comfy_UI\\python_embeded\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '/LIBPATH:C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\lib\\x64', '/LIBPATH:D:\\Comfy_UI\\python_embeded\\libs', '/LIBPATH:D:\\Comfy_UI\\python_embeded\\libs', '/LIBPATH:D:\\Comfy_UI\\python_embeded\\libs', '/LIBPATH:C:\\Python311\\libs', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64', 'cuda.lib', '/OUT:C:\\Users\\win11\\AppData\\Local\\Temp\\tmp1qwypcg6\\cuda_utils.cp311-win_amd64.pyd']' returned non-zero exit status 2.

**Comment by tiandaoyuxi** [comment]
C:\Windows\System32>cl
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.41.34120 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]

C:\Windows\System32>paxas --version
'paxas' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Windows\System32>ptxas --version
ptxas: NVIDIA (R) Ptx optimizing assembler
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:38:26_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by 18900891991** [comment]
subprocess.CalledProcessError: Command '['E:\\mingw64\\bin\\gcc.EXE', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpzwv6gf4q\\main.c', '-O3', '-shared', '-IE:\\ComfyUI-aki-v1.3\\python\\lib\\site-packages\\triton\\common\\..\\third_party\\cuda\\include', '-IE:\\ComfyUI-aki-v1.3\\python\\Include', '-IC:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpzwv6gf4q', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.4\\lib\\x64', '-LE:\\ComfyUI-aki-v1.3\\python\\libs', '-lcuda', '-o', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpzwv6gf4q\\cuda_utils.cp310-win_amd64.pyd']' returned non-zero exit status 1.

The same problem.

**Comment by tiandaoyuxi** [comment]
D:\Comfy_UI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-05 09:46:15.044964
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\Comfy_UI\python_embeded\python.exe
** ComfyUI Path: D:\Comfy_UI\ComfyUI
** Log path: D:\Comfy_UI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\Comfy_UI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   4.4 seconds: D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 130852 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3

**Comment by tiandaoyuxi** [comment]
triton                                  3.1.0
sageattention                           1.0.6

**Comment by tiandaoyuxi** [comment]
updata C:\Users\win11>ptxas --version
ptxas: NVIDIA (R) Ptx optimizing assembler
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Sep_12_02:47:25_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.77
Build cuda_12.6.r12.6/compiler.34841621_0   11.8 to 12.6

**Comment by PGCRT** [comment]
Got triton 3.1.0, sageattention 1.0.6, CUDA 12.6, all PATH environments are properly setup, VS build tools components installed


      ```Command '['C:\\Program Files (x86)\\Microsoft Visual 
         Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\Hostx64\\x64\\cl.EXE',
         'C:\\Users\\PGC\\AppData\\Local\\Temp\\tmpbztlr_rc\\main.c',
         '/nologo', '/O2', '/LD', '/wd4819',
         '/ID:\\SD\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\triton\\backends\\nvidia\\include',
         '/IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\include',
         '/IC:\\Users\\PGC\\AppData\\Local\\Temp\\tmpbztlr_rc',
         '/ID:\\SD\\ComfyUI_windows_portable\\python_embeded\\Include',
         '/IC:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\include',
         '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared',
         '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt',
         '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um',
         '/link',
         '/LIBPATH:D:\\SD\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\triton\\backends\\nvidia\\lib',
         '/LIBPATH:C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\lib\\x64',
         '/LIBPATH:D:\\SD\\ComfyUI_windows_portable\\python_embeded\\libs',
         '/LIBPATH:C:\\Python312\\libs',
         '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\lib\\x64',
         '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\x64',
         '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64',
         'cuda.lib',
         '/OUT:C:\\Users\\PGC\\AppData\\Local\\Temp\\tmpbztlr_rc\\cuda_utils.cp312-win_amd64.pyd']' returned non-zero exit status 2.```

**Comment by Nightnightlight** [comment]
I get the same error as above.

**Comment by Bocchi-Chan2023** [comment]
OK I found why,
https://github.com/woct0rdho/triton-windows/releases/tag/v3.0.0-windows.post1
extract zips depends on your python version.

**Comment by tiandaoyuxi** [comment]
> 好的，我找到了原因， https://github.com/woct0rdho/triton-windows/releases/tag/v3.0.0-windows.post1 提取 zips 取決於你的 python 版本。
How to use it,[python_3.11.9_include_libs.zip](https://github.com/woct0rdho/triton-windows/releases/download/v3.0.0-windows.post1/python_3.11.9_include_libs.zip)

 I have installed it [triton-3.0.0-cp311-cp311-win_amd64.whl](https://github.com/woct0rdho/triton-windows/releases/download/v3.0.0-windows.post1/triton-3.0.0-cp311-cp311-win_amd64.whl)
pip list  
show  “Triton 3.1.0”

**Comment by tiandaoyuxi** [comment]
> OK I found why, https://github.com/woct0rdho/triton-windows/releases/tag/v3.0.0-windows.post1 extract zips depends on your python version.

cool  thx！
