### ISSUE TITLE
Can we have an image to video example?

### ISSUE THREAD

**Issue by harrywenjie** [kijai/ComfyUI-HunyuanVideoWrapper#26]
Currently, there is only t2v and v2v examples. 
Can we have an image to video example?
Thank you

**Comment by kijai** [comment]
There is no image2video model released yet.

**Comment by cchance27** [comment]
The company said a img2vid model is coming though I don’t see why a less optimal version shouldn’t work with this model especially since v2v is working so well

that said I’m more concerned with sdpa working as the other  attentions I think don’t work on some hardware
