### ISSUE TITLE
timm==0.6.13

### ISSUE THREAD

**Issue by lunatico67** [kijai/ComfyUI-HunyuanVideoWrapper#27]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
image-reward 1.5 requires timm==0.6.13, but you have timm 0.9.16 which is incompatible.

**Comment by kijai** [comment]
I don't know how that's related to these nodes, image-reward isn't even used?

**Comment by lunatico67** [comment]
Hi Kijai
No problem, workflows are loaded in their entirety without any problems.
When I installed it ,in the comfyui console, this was written in red and I wanted to mention it to know what it was but if you say that it is not related to this custom node, nothing happens, strange things of computer science.
A lot of thanks for your amazing contribution to comfyui with your custom nodes.
Best Dreams
