### ISSUE TITLE
Error at HY Sampler Vid2Vid

### ISSUE THREAD

**Issue by yogotatara3** [kijai/ComfyUI-HunyuanVideoWrapper#28]
Hey, thx for wrapping Hunyuan.

I get this error do you know what the reason could be for this.
Thanks in regard.

Error:
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\Hostx64\\x64\\cl.EXE', 'C:\\Users\\RAIINS~1\\AppData\\Local\\Temp\\tmpt26nlz2m\\main.c', '/nologo', '/O2', '/LD', '/wd4819', '/IC:\\tools\\StabilityMatrix\\Packages\\ComfyUI\\venv\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '/IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5\\include', '/IC:\\Users\\RAIINS~1\\AppData\\Local\\Temp\\tmpt26nlz2m', '/IC:\\tools\\StabilityMatrix\\Packages\\ComfyUI\\venv\\Scripts\\Include', '/IC:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\include', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt', '/IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um', '/link', '/LIBPATH:C:\\tools\\StabilityMatrix\\Packages\\ComfyUI\\venv\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '/LIBPATH:C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5\\lib\\x64', '/LIBPATH:C:\\tools\\StabilityMatrix\\Packages\\ComfyUI\\venv\\Scripts\\libs', '/LIBPATH:C:\\tools\\StabilityMatrix\\Packages\\ComfyUI\\venv\\libs', '/LIBPATH:C:\\tools\\StabilityMatrix\\Packages\\ComfyUI\\venv\\Scripts\\libs', '/LIBPATH:C:\\Python310\\libs', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64', 'cuda.lib', '/OUT:C:\\Users\\RAIINS~1\\AppData\\Local\\Temp\\tmpt26nlz2m\\cuda_utils.cp310-win_amd64.pyd']' returned non-zero exit status 2.

**Comment by kijai** [comment]
It's an issue with the compilation setup for triton/sageattention, not that simple to solve as it's very system dependent. 

If you didn't follow this guide yet, it's a good starting point:

https://purz.notion.site/Get-Windows-Triton-working-for-Mochi-6a0c055e21c84cfba7f1dd628e624e97

**Comment by yogotatara3** [comment]
Wierd I already have Triton installed with this guide. 
Worked super well for Mochi. I dont understand why its not working with Hunyuan

**Comment by kijai** [comment]
> Wierd I already have Triton installed with this guide. Worked super well for Mochi. I dont understand why its not working with Hunyuan.
> 
> But ok thx for the hint. Worked with SDPA now but is quite slow

For Hunyuan we need to use the sageattn_varlen -function which was added in 1.0.6, I think the issue is that this also needs newer Triton, so make sure you have the 3.1.0.

Sdpa generally doesn't seem to work well, if at all with this code as it is.

**Comment by yogotatara3** [comment]
I have 3.1.0
<img width="369" alt="Bildschirmfoto 2024-12-05 um 10 53 19" src="https://github.com/user-attachments/assets/6d957f3a-99e0-49c6-870d-dc11425583cd">

**Comment by kijai** [comment]
You can also still try re-installing that, and also clearing the Triton cache, which is located in the Users folder, on Windows that would be:

`C:\Users\username\.triton`

Also possibly needs newer cuda-toolkit, this I'm not sure of, personally I'm using the current latest 12.6 version.

**Comment by yogotatara3** [comment]
will try, thanks for your tips
