### ISSUE TITLE
some nodes are missing, cant find in comfyui manager

### ISSUE THREAD

**Issue by mehulgupta2016154** [kijai/ComfyUI-HunyuanVideoWrapper#31]
![{0025AA02-7B2B-43F4-A3AF-578A208094B3}](https://github.com/user-attachments/assets/19edb756-ceb9-4b23-97c9-e10b8919aa21)
When loading the pipeline for hunyuan-video , getting this issue. Kept all the files/model weights as suggested. Cant find the missing nodes in manager as well

**Comment by doogyhatts** [comment]
Use the option to install via git url.

**Comment by kijai** [comment]
The missing nodes are these nodes themselves... check your startup log for possible import errors, especially any "module not found" and such to give an idea what actually is missing, probably some dependency.

**Comment by nzmajid77** [comment]
I got the same problem. I have updated my ComfyUI, still cannot find the missing nodes.

**Comment by nzmajid77** [comment]
> Use the option to install with git url.

How to do this?

**Comment by kijai** [comment]
These nodes are now available in the Manager.
