### ISSUE TITLE
[Feat] GGUF Support

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [kijai/ComfyUI-HunyuanVideoWrapper#35]
The GGUF appears to be very suitable for this model, as its quality has not deteriorated in FP8.

**Comment by cchance27** [comment]
Ya this is a major request i'd love to see done since Mac's dont support FP8 (though we also would need SDPA which is apparently broken still)

**Comment by Bocchi-Chan2023** [comment]
> Ya this is a major request i'd love to see done since Mac's dont support FP8 (though we also would need SDPA which is apparently broken still)

just use sageattention btw

**Comment by doogyhatts** [comment]
I am going to test the BF16 model first with the same settings, on a workstation GPU, to see if it is the FP8 that results in incorrect anatomy. Other than that, Kijai said in an earlier post that he doesn't have the time to work on it now. 

And I don't think city96 is going to work on it either as this does not seem directly compatible to the existing gguf loaders. But you can try asking him too.

**Comment by cchance27** [comment]
I thought sage wasn’t on mps Sent from my iPhoneOn Dec 5, 2024, at 10:04 PM, edwin zeng ***@***.***> wrote:﻿
I am going to test the BF16 model first with the same settings, on a workstation GPU, to see if it is the FP8 that results in incorrect anatomy. Other than that, Kijai said in an earlier post that he doesn't have the time to work on it now.
And I don't think city96 is going to work on it either as this does not seem directly compatible to the existing gguf loaders. But you can try asking him too.

**Comment by doogyhatts** [comment]
> I thought sage wasn’t on mps 
mps? 

Anyway, I did some generations using the BF16 model earlier today. I did use SageAttention-1 on the A40.
The results are described in this post.
https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/issues/4#issuecomment-2524942713

**Comment by nitinmukesh** [comment]
> mps?

Mac

**Comment by doogyhatts** [comment]
The team doing SVDQuant is looking to see if they can apply their solution to optimise Hunyuan Video, instead of using GGUF.
https://github.com/mit-han-lab/nunchaku/issues/42

**Comment by kijai** [comment]
> The team doing SVDQuant is looking to see if they can apply their solution to optimise Hunyuan Video, instead of using GGUF. [mit-han-lab/nunchaku#42](https://github.com/mit-han-lab/nunchaku/issues/42)

This is the one to wait for indeed.

**Comment by kijai** [comment]
Not going to happen for the wrapper though.
