### ISSUE TITLE
Would there be GGUF versions of the model?

### ISSUE THREAD

**Issue by doogyhatts** [kijai/ComfyUI-HunyuanVideoWrapper#4]
Just curious actually about the output quality as a comparison between the different precisions and quants.
fp8 vs gguf q4
fp16 vs gguf q8

**Comment by sunnyyangyangyang** [comment]
q8 is better than fp8 for flux

**Comment by doogyhatts** [comment]
I tried FP8, its not feasible for human depictions as the output I got has the human arms merged between two people.

**Comment by kijai** [comment]
> I tried FP8, its not feasible for human depictions as the output I got has the human arms merged between two people.

And you deducted this is because of the quant by running the exact same thing with bf16? Because if not, that's not helpful at all. Fp8 has been perfectly fine in my testing, may try GGUF at some point but it's not a personal priority as it will slow things down.

**Comment by doogyhatts** [comment]
In that case, I will use the bf16 model instead.

**Comment by tdrminglin** [comment]
> > I tried FP8, its not feasible for human depictions as the output I got has the human arms merged between two people.
> 
> And you deducted this is because of the quant by running the exact same thing with bf16? Because if not, that's not helpful at all. Fp8 has been perfectly fine in my testing, may try GGUF at some point but it's not a personal priority as it will slow things 

May I ask a question? This model is like Cogvideo1.5, only supports bf16 inference? My GPU doesn't support bf16, so I tried fp16 (by altering some codes) ,also got black video.

**Comment by doogyhatts** [comment]
> May I ask a question? This model is like Cogvideo1.5, only supports bf16 inference? My GPU doesn't support bf16, so I tried fp16 (by altering some codes) ,also got black video.

It supports both bf16 and fp8 inference, as two separate models.
To use the bf16 model, I remember setting the quant option to be disabled because there is no "bf16" option.

**Comment by kijai** [comment]
> > > I tried FP8, its not feasible for human depictions as the output I got has the human arms merged between two people.
> > 
> > 
> > And you deducted this is because of the quant by running the exact same thing with bf16? Because if not, that's not helpful at all. Fp8 has been perfectly fine in my testing, may try GGUF at some point but it's not a personal priority as it will slow things
> 
> May I ask a question? This model is like Cogvideo1.5, only supports bf16 inference? My GPU doesn't support bf16, so I tried fp16 (by altering some codes) ,also got black video.

The original weights are in bf16, so it's possible to cause issues. Bigger issue still is the memory use at fp/bf16 over smaller quants though.

**Comment by tdrminglin** [comment]
> > May I ask a question? This model is like Cogvideo1.5, only supports bf16 inference? My GPU doesn't support bf16, so I tried fp16 (by altering some codes) ,also got black video.
> 
> It supports both bf16 and fp8 inference, as two separate models. To use the bf16 model, I remember setting the quant option to be disabled because there is no "bf16" option.

I was using the fp8 version ,and set the nodes options. by defalut ,I'd recieve an error telling me that my card doesn't support bf16. so I changed some codes and bypassed that error ,which resulted in black video

**Comment by tdrminglin** [comment]
> > > > I tried FP8, its not feasible for human depictions as the output I got has the human arms merged between two people.
> > > 
> > > 
> > > And you deducted this is because of the quant by running the exact same thing with bf16? Because if not, that's not helpful at all. Fp8 has been perfectly fine in my testing, may try GGUF at some point but it's not a personal priority as it will slow things
> > 
> > 
> > May I ask a question? This model is like Cogvideo1.5, only supports bf16 inference? My GPU doesn't support bf16, so I tried fp16 (by altering some codes) ,also got black video.
> 
> The original weights are in bf16, so it's possible to cause issues. Bigger issue still is the memory use at fp/bf16 over smaller quants though.

I get it ,thanks!

**Comment by doogyhatts** [comment]
> I was using the fp8 version ,and set the nodes options. by defalut ,I'd recieve an error telling me that my card doesn't support bf16. so I changed some codes and bypassed that error ,which resulted in black video

Was there be any incorrect settings for the model loading node?
Honestly, I did not encounter such an error before.
Which GPU are you using?

**Comment by tdrminglin** [comment]
> > I was using the fp8 version ,and set the nodes options. by defalut ,I'd recieve an error telling me that my card doesn't support bf16. so I changed some codes and bypassed that error ,which resulted in black video
> 
> Was there be any incorrect settings for the model loading node? Honestly, I did not encounter such an error before. Which GPU are you using?

I'm using 2080ti 22G. As kijai said ,the original modal is bf16. I had the same issue with cogvideo1.5, also bf16. I think only GPU with Ampere and above structures can run this model.

**Comment by doogyhatts** [comment]
> I'm using 2080ti 22G. As kijai said ,the original modal is bf16. I had the same issue with cogvideo1.5, also bf16. I think only GPU with Ampere and above structures can run this model.

In this case, you will have to rent a suitable GPU on a Linux system, from a cloud service provider.

**Comment by doogyhatts** [comment]
Ok the A40 GPU finally became available again for me to rent it at $0.434 per hour.
I was able to generate a mix of 14 videos for a cost of $1.56 usd, inclusive of installation costs at 30 cents.

So I wanted to check if the BF16 model can give better anatomy and fingers.
Incorrect anatomy in this case, it means "merged arms" with two people in close proximity to each other.

I found that there are situations when both the FP8 and BF16 models will output incorrect anatomies under the same settings, such as having insufficient steps and low guidance scale. To fix the anatomy, I had increased the guidance scale to 5-6 and steps to 50. There is also a situation where the FP8 model will output with an incorrect anatomy while the BF16 model outputs a correct one.

In all situations, the output fingers from both models are not good, especially in confined regions. Sometimes, the BF16 model can output better fingers than the FP8 one. But the fingers output from both models underperformed when compared to Minimax, even though Minimax itself is also not perfect.

I also found out that the BF16 model has no impact to the generation time, it remained the same with the FP8 model.
So now I have a better understanding on what the GGUF Q8 model would output.
But in the absence of this GGUF Q8 model, I would use the BF16 one instead, hopefully next time on 2x3090, and reduce the generation time by half.

I do have the video outputs but they are somewhat nsfw, so I am not sharing them here.

**Comment by tdrminglin** [comment]
> > I'm using 2080ti 22G. As kijai said ,the original modal is bf16. I had the same issue with cogvideo1.5, also bf16. I think only GPU with Ampere and above structures can run this model.
> 
> In this case, you will have to rent a suitable GPU on a Linux system, from a cloud service provider.

no need now, I‘ve finally managed to make it run on my GPU

**Comment by se7enth** [comment]
> > > I'm using 2080ti 22G. As kijai said ,the original modal is bf16. I had the same issue with cogvideo1.5, also bf16. I think only GPU with Ampere and above structures can run this model.
> > 
> > 
> > In this case, you will have to rent a suitable GPU on a Linux system, from a cloud service provider.
> 
> no need now, I‘ve finally managed to make it run on my GPU

how to do? could you share the solution? My GPU also is  2080ti 22G.
