### ISSUE TITLE
"comfy" attention mode not working

### ISSUE THREAD

**Issue by gitanon112** [kijai/ComfyUI-HunyuanVideoWrapper#42]
When trying to use comfy attention mode with torch.compile, it fails with: 
```
HyVideoSampler
backend='inductor' raised:
AssertionError: increase TRITON_MAX_BLOCK['X'] to 2097152

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
import torch._dynamo
torch._dynamo.config.suppress_errors = True
```

When trying to use comfy attention mode without torch.compile, keep getting OOM error. Let me know if any additional info is needed, thanks!

**Comment by kijai** [comment]
Do you have xformers installed? I noticed it doesn't work with that, which is what comfy defaults to if it's installed. You can launch comfy with --disable-xformers, but that should then be same as just selecting sdpa.
