### ISSUE TITLE
我本地的llm怎么读取，我不在线下载？

### ISSUE THREAD

**Issue by MikeAiJF** [kijai/ComfyUI-HunyuanVideoWrapper#46]
为什么本地的llm无法读取，我不想在线下载

**Comment by doogyhatts** [comment]
你问的是中文是否可以用大型语言模型吗？

**Comment by MikeAiJF** [comment]
![image](https://github.com/user-attachments/assets/2e31cf02-a6e3-40af-b819-a7c432046654)
这个为什么读取不了本地模型，非要在线下载吗，我是下载后放在指定文件夹，但是看不到

**Comment by doogyhatts** [comment]
这是我的 LLM 模型路径。检查你的是否正确。
/ComfyUI/models/LLM/

我必须这样做：
git clone https://huggingface.co/Kijai/llava-llama-3-8b-text-encoder-tokenizer/

之后，我删除了四个 safetensors 模型。然后我手动将它们下载到文件夹中。
wget https://huggingface.co/Kijai/llava-llama-3-8b-text-encoder-tokenizer/resolve/main/model-00001-of-00004.safetensors
wget https://huggingface.co/Kijai/llava-llama-3-8b-text-encoder-tokenizer/resolve/main/model-00002-of-00004.safetensors
wget https://huggingface.co/Kijai/llava-llama-3-8b-text-encoder-tokenizer/resolve/main/model-00003-of-00004.safetensors
wget https://huggingface.co/Kijai/llava-llama-3-8b-text-encoder-tokenizer/resolve/main/model-00004-of-00004.safetensors

现在所有内容都位于该目录中。
/ComfyUI/models/LLM/llava-llama-3-8b-text-encoder-tokenizer/

**Comment by MikeAiJF** [comment]
![image](https://github.com/user-attachments/assets/0044d848-3451-40e3-8245-01324e8bb701)

**Comment by doogyhatts** [comment]
您是否检查过这四个模型文件的大小是否正确？
Have you checked if the four model files have the correct sizes?

**Comment by huoxingzhake** [comment]
Yes, I also encountered this problem, you can add one without automatic download, because automatic download will be in c disk

**Comment by currenttime** [comment]
配置的extra_model_paths也没有生效，即使文件夹中已经有了llava模型，只能在线下载到/ComfyUI/models/LLM/这里

**Comment by ccckobe** [comment]
> Yes, I also encountered this problem, you can add one without automatic download, because automatic download will be in c disk

请问，具体是加一个非自动下载的node吗，还是在哪里可以把这个自动下载属性关掉（这两个都没能找到）？我用的是comfyui桌面版本并装在其他盘因为C盘空间不够，如currenttime提到的一样的问题，(down)load hunyuan video textencoder节点似乎不能识别除c盘默认的那个程序路径以外的其他路径,哪怕已经设置为base path,并且在其他常规模型节点中可以读取。
