### ISSUE TITLE
RuntimeError: `ptxas` failed with error code 4294967295

### ISSUE THREAD

**Issue by kanfengjingderen** [kijai/ComfyUI-HunyuanVideoWrapper#48]
HyVideoSampler `ptxas` failed with error code 4294967295. Pls kindly help with thanks

File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\nvidia\compiler.py", line 312, in make_cubin
    raise RuntimeError(f'`ptxas` failed with error code {e.returncode}: \n{log}')
RuntimeError: `ptxas` failed with error code 4294967295:

**Comment by hlufeng** [comment]
Did you solve it? It happened to me

**Comment by vigourwu** [comment]
> HyVideoSampler `ptxas` failed with error code 4294967295. Pls kindly help with thanks
> 
> File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\nvidia\compiler.py", line 312, in make_cubin raise RuntimeError(f'`ptxas` failed with error code {e.returncode}: \n{log}') RuntimeError: `ptxas` failed with error code 4294967295:

How it was sloved?

**Comment by kanglehao** [comment]
> Did you solve it? It happened to me

triton在windows上没装好或者不兼容, attention_mode使用其他方式或者安装其他版本triton 我是2080ti 一样的问题, 换了其他方式triton 不知道装哪个版本

**Comment by zslefour** [comment]
从错误信息中发现，不管base_precision选择bf16还是fp16，到了Sampler还是要求bf16，而2080ti不支持bf16，开来是无解
--------------错误信息------------------------------
ptxas C:\Users\...\AppData\Local\Temp\tmpumohz431.ptx, line 387; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas C:\Users\...\AppData\Local\Temp\tmpumohz431.ptx, line 387; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
.........
!!! Exception during processing !!! `ptxas` failed with error code 4294967295
