### ISSUE TITLE
HyVideoModelLoader  'img_in.proj.weight'

### ISSUE THREAD

**Issue by MelvinMik** [kijai/ComfyUI-HunyuanVideoWrapper#51]
When loading the video model, it gives me this error:'img_in.proj.weight' is that due to a wrong model as text encode? Would be weird since its auto-download.

**Comment by kijai** [comment]
That is about the video model, not text encoder at all, the video model is not autodownloaded.

**Comment by MelvinMik** [comment]
I'm currently redownloading ur models I think i took the one from the original hy repo thx.

**Comment by kijai** [comment]
> I'm currently redownloading ur models I think i took the one from the original hy repo thx.

That would explain it, the original won't work as it's packed differently than .safetensors allows.

**Comment by Bzcy520** [comment]
如何解决 我在CIVITAI重新下载了模型 但是不起作用.

**Comment by Bzcy520** [comment]
在COMFYUI 管理其中更新了 也没用

**Comment by benlcd** [comment]
> 在COMFYUI 管理其中更新了 也没用

Do you find the solution ? i have the same issue

**Comment by Bzcy520** [comment]
> > 在COMFYUI 管理其中更新了 也没用
> 
> 您找到解决方案了吗？我有同样的问题

似乎是模型的问题，之前是在Civitai下载的模型。现在我换成了在这里下载模型，https://www.modelscope.cn/models/Kijai/HunyuanVideo_comfy/files 没有出现那样的提示了
