### ISSUE TITLE
DownloadAndLoadHyVideoTextEncoder - 'CLIPModel' object has no attribute 'norm'

### ISSUE THREAD

**Issue by smithsun00** [kijai/ComfyUI-HunyuanVideoWrapper#52]
Hi
I am getting this error every time I am trying to queue the workflow, any workflow for that matter.
I downloaded all files and placed them in the correct folders, but something seems to still not work correctly.

I have a Geforce 4090, and am using cuda 11.8
Any help would be appreciated.

Here is the stack trace around the error:
`Loading text encoder model (clipL) from: F:\AI\ImageGeneration\CUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: F:\AI\ImageGeneration\CUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
Loading text encoder model (llm) from: F:\AI\ImageGeneration\CUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
!!! Exception during processing !!! 'CLIPModel' object has no attribute 'norm'`

Update:
This is now resolved. Apparently I copied the files incorrectly to the tokenizer folder.

**Comment by RuneGjerde** [comment]
Same error here
