### ISSUE TITLE
Auto-trim v2v source videos that do not match the video_length-1 must be divisble by 4

### ISSUE THREAD

**Issue by SoftologyPro** [kijai/ComfyUI-HunyuanVideoWrapper#53]
Could this be auto-set for videos that do not have a frame count divisble by 4? Crop the last 1-3 frames as necessary when processing starts?

Otherwise the user needs to use some editing software to trim the videos themselves before loading?

Also set the target FPS to match the source once loaded.

**Comment by gaoxuxu110** [comment]
same problem, by the way the video resolution I uploaded is 512 x 720

**Comment by Lumabrik** [comment]
This isnt nessasry, the i comfy  Load Video node that lets you specify the video length and start frames regardless of the videos frame count.

**Comment by SoftologyPro** [comment]
OK, then shouldn't the video length be auto-set to the video length (and adjusted however many 1-3 frames is needed) at load time so the error does not happen for users?

**Comment by kijai** [comment]
Lots of things like this of course could be automated, in my experience if I do something like that automatically, then people ask why the end result is shorter etc. 

The error could be clearer though.

**Comment by SoftologyPro** [comment]
But now it is much shorter right?  Fixed at 101 no matter what the input.
You only have to adjust taking off at most 3 frames to get the right length.  Nobody will notice that.
And setting the output resolution to match the input should be default right?
For video to video the user expects the same length and resultion movie to be output after processing.

Rather than fixing the error message, fix the length and have a popup "The output movie length, width and height have been adjusted to match your input video"

**Comment by kijai** [comment]
>  For video to video the user expects the same length and resultion movie to be output after processing.

But that's exactly my point, it would not same length be if it was automatically cropped to a supported length?

**Comment by SoftologyPro** [comment]
But you only need to crop it up to 3 frames to match the requirement right?

**Comment by abozahran** [comment]
> But you only need to crop it up to 3 frames to match the requirement right?

![image](https://github.com/user-attachments/assets/3d7db0ce-c491-49e3-a5df-83602cc30319)

how i can fix that it happens when using video length 6 or 8 second and tried 1 miuntes long and no problem appeared

![image](https://github.com/user-attachments/assets/17d4784e-9b10-42ad-9cf3-412d1ea0ca42)

**Comment by kijai** [comment]
> > But you only need to crop it up to 3 frames to match the requirement right?
> 
> ![image](https://private-user-images.githubusercontent.com/107565623/393585226-3d7db0ce-c491-49e3-a5df-83602cc30319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTI1OTcsIm5iZiI6MTczMzY1MjI5NywicGF0aCI6Ii8xMDc1NjU2MjMvMzkzNTg1MjI2LTNkN2RiMGNlLWM0OTEtNDllMy1hNWRmLTgzNjAyY2MzMDMxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxMDA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDNlNjExZTYzZjVlMWM3YmU5MjM0MTg4Y2UxY2JmOGM4ZDBiMDkyNjczMWVhY2I2OWEyODBiNzQzMzJiMTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1f2Ezh6-tQ4jV7EEwhrMpPzJFGRP7aMAtTs6Vaxstxk)
> 
> how i can fix that it happens when using video length 6 or 8 second and tried 1 miuntes long and no problem appeared
> 
> ![image](https://private-user-images.githubusercontent.com/107565623/393585289-17d4784e-9b10-42ad-9cf3-412d1ea0ca42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTI1OTcsIm5iZiI6MTczMzY1MjI5NywicGF0aCI6Ii8xMDc1NjU2MjMvMzkzNTg1Mjg5LTE3ZDQ3ODRlLTliMTAtNDJhZC05Y2YzLTQxMmQxZWEwY2E0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxMDA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDk4ODAxNTUwNWE4OTJlNTFlYTY1NGFlMjg2YWM0ZDBlYWE2NTllZTg5M2UzNTY3MjBmMzE3ZDkwMzZlYTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7dlUpsJxw_d4tixAcyy5pfSDllf6mxMc9ufg0oVHcOQ)

You are selecting every 3rd frame there, the cap looks fine but perhaps your video doesn't have enough frames to reach 101 then?

**Comment by PGCRT** [comment]
You can setup a slider like this
https://github.com/user-attachments/assets/4b4f2da3-6d5e-4759-8fe3-c2120ac0b179
