### ISSUE TITLE
Help - Every output complete nonsense

### ISSUE THREAD

**Issue by ctf05** [kijai/ComfyUI-HunyuanVideoWrapper#58]
Below is the workflow I created based on your template. I do string replacement to customize some aspects. I wanted to make a ready to go workflow to easily call. My problem is, I have tried many prompts and your red panda prompt and all of then get a weird green booger with minimal relation to the prompt. Pleas help!

{
  "1": {
    "class_type": "HyVideoModelLoader",
    "inputs": {
      "model_name": "hyvideo/hunyuan_video_720_fp8_e4m3fn.safetensors",
      "base_precision": "bf16",
      "load_device": "offload_device",
      "quantization": "fp8_e4m3fn",
      "model": "hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors"
    }
  },
  "3": {
    "class_type": "HyVideoSampler",
    "inputs": {
      "model": ["1", 0],
      "hyvid_embeds": ["30", 0],
      "width": |width|,
      "height": |height|,
      "num_frames": |num_frames|,
      "steps": |steps|,
      "seed": 0,
      "flow_shift": 1,
      "embedded_guidance_scale": 1,
      "force_offload": false
    }
  },
  "7": {
    "class_type": "HyVideoVAELoader",
    "inputs": {
      "model_name": "hunyuan_video_vae_bf16.safetensors",
      "precision": "fp16"
    }
  },
  "16": {
    "class_type": "DownloadAndLoadHyVideoTextEncoder",
    "inputs": {
      "clip_model": "openai/clip-vit-large-patch14",
      "llm_model": "Kijai/llava-llama-3-8b-text-encoder-tokenizer",
      "precision": "fp16"
    }
  },
  "30": {
    "class_type": "HyVideoTextEncode",
    "inputs": {
      "text_encoders": ["16", 0],
      "prompt": "|prompt|",
      "negative": "|negative_prompt|"
    }
  },
  "34": {
    "class_type": "VHS_VideoCombine",
    "inputs": {
      "images": ["5", 0],
      "frame_rate": |fps|,
      "loop_count": 0,
      "filename_prefix": "HunyuanVideo",
      "format": "video/h264-mp4",
      "pix_fmt": "yuv420p",
      "crf": 19,
      "save_metadata": false,
      "pingpong": false,
      "save_output": true
    }
  },
  "5": {
    "class_type": "HyVideoDecode",
    "inputs": {
      "vae": ["7", 0],
      "samples": ["3", 0],
      "enable_vae_tiling": true,
      "temporal_tiling_sample_size": 8
    }
  }
}

**Comment by kijai** [comment]
What is this is .json supposed to be exactly? The sampler values on it make no sense, are you feeding them from somewhere else?

**Comment by ctf05** [comment]
Hi Kijai, thanks for taking the time to help. Basically, I have never used ComfyUI before and am trying to make a Runpod serverless instance of your wrapper and ComfyUI. I have this JSON stored on the instance. This JSON is my workflow. In the instance, I replace all of the placeholder values with pipes with actual data before sending the workflow. I send the workflow using urllib.request.Request(f"http://{COMFY_HOST}/prompt", data=data). I am hosting a ComfyUI server on the instance then doing an API call to the local server. Sorry if I am wildly misled on how workflows work. How I made this JSON was I looked at your example workflow T2V, took only the nodes I needed and for each node, chose one of the "widget values" you had and put that as the input.

**Comment by kijai** [comment]
> "flow_shift": 1,
> "embedded_guidance_scale": 1,

What I mean is that these values, if they are actually the values used, are completely wrong, default flow_shift is 9.0 and guidance scale 6.0. Also I don't see the newer widgets I've added such as denoise etc. which makes me think the nodes aren't up to date?

**Comment by ctf05** [comment]
{
  "1": {
    "class_type": "HyVideoModelLoader",
    "inputs": {
      "model": "hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors",
      "base_precision": "bf16",
      "quantization": "fp8_e4m3fn",
      "load_device": "main_device",
      "attention_mode": "sageattn_varlen"
    }
  },
  "3": {
    "class_type": "HyVideoSampler",
    "inputs": {
      "width": |width|,
      "height": |height|,
      "num_frames": |num_frames|,
      "steps": |steps|,
      "guidance_scale": 6,
      "flow_shift": 9,
      "seed": 3,
      "control_after_generate": "fixed",
      "force_offload": true,
      "denoise_strength": 1,
      "hyvid_embeds": ["30", 0],
      "embedded_guidance_scale": 1,
      "model": ["1", 0]
    }
  },
  "7": {
    "class_type": "HyVideoVAELoader",
    "inputs": {
      "model_name": "hunyuan_video_vae_bf16.safetensors",
      "precision": "fp16"
    }
  },
  "16": {
    "class_type": "DownloadAndLoadHyVideoTextEncoder",
    "inputs": {
      "llm_model": "Kijai/llava-llama-3-8b-text-encoder-tokenizer",
      "clip_model": "openai/clip-vit-large-patch14",
      "precision": "fp16"
    }
  },
  "30": {
    "class_type": "HyVideoTextEncode",
    "inputs": {
      "prompt": "|prompt|",
      "negative": "|negative_prompt|",
      "force_offload": true,
      "text_encoders": ["16", 0]
    }
  },
  "34": {
    "class_type": "VHS_VideoCombine",
    "inputs": {
      "images": ["5", 0],
      "frame_rate": |fps|,
      "loop_count": 0,
      "filename_prefix": "HunyuanVideo",
      "format": "video/h264-mp4",
      "pix_fmt": "yuv420p",
      "crf": 19,
      "save_metadata": false,
      "pingpong": false,
      "save_output": true
    }
  },
  "5": {
    "class_type": "HyVideoDecode",
    "inputs": {
      "vae": ["7", 0],
      "samples": ["3", 0],
      "enable_vae_tiling": true,
      "temporal_tiling_sample_size": 16
    }
  }
}

Thanks for the comments. I think I made some progress. These are my current settings. My new problem is I am getting the below error. It is on a RTX 3090 24gb vram. Does anything catch your eye or do you have any tips to lower VRAM usage?
"
torch.OutOfMemoryError: Allocation on device
Got an OOM, unloading all loaded models.
"

**Comment by kijai** [comment]
That's just running out of memory, either have to reduce resolution/frame count or use the block_swap feature as outlined in the example workflow for it.

**Comment by ctf05** [comment]
It does work with a 48gb GPU but the max ram it allocated was 13gb. It is weird it cant work on a lower VRAM GPU. Do you know why this is or how to fix it?

**Comment by ctf05** [comment]
I fixed it. I added "quantization": "bnb_nf4" to node 16
