### ISSUE TITLE
Error message when loading example workflow

### ISSUE THREAD

**Issue by git523** [kijai/ComfyUI-HunyuanVideoWrapper#6]
Not sure what caused this error...
![error](https://github.com/user-attachments/assets/430c4a31-d0d8-45d7-a5ea-54e797a07186)

**Comment by git523** [comment]
there is also an alert message on the top right corner:
![error2](https://github.com/user-attachments/assets/ba14ca7d-99f4-426d-8675-524a32cb2a58)

**Comment by kijai** [comment]
It's not an error from these nodes, but from the VHS nodes....I'd suggest trying to update them and/or ComfyUI itself.

**Comment by git523** [comment]
Thanks and I switched to pinokio environment, and now the error message disappeared. But now there is a new error of "HyVideoSampler: expected str, bytes or os.PathLike object, not NoneType", i will start a new thread since it is not related to this thread.
