### ISSUE TITLE
What was changed to make sdpa work?

### ISSUE THREAD

**Issue by tdrminglin** [kijai/ComfyUI-HunyuanVideoWrapper#60]
My goal is to make the model run on my 2080ti GPU, I tried to change the base_dtype =torch.float32 in pipeline_hunyuan_video.py. In the last version of ComfyUI-HunyuanVideoWrapper , after I changed this , if I choose sageattention as attention mode, I get a triton error when it comes to sampling:
` File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\triton\compiler\compiler.py", line 378, in _init_handles
    raise OutOfResources(self.metadata.shared, max_shared, "shared memory")
triton.runtime.errors.OutOfResources: out of resource: shared memory, Required: 67584, Hardware limit: 65536. Reducing block sizes or `num_stages` may help.`
So I choose sdpa in the older version, then I got a super blurry video just like other issues have descriped, other than black video ,this implies the model may actually work on my GPU.
Then I updated the  ComfyUI-HunyuanVideoWrapper to the latest version today and  also changed the base_dtype in pipeline_hunyuan_video.py. The error with  sageattention remains the same. But when I choose sdpa mode, it outputs black video again. 
So may I ask what was changed to sdpa  ? So I can manually change that part **only** ,to test if it will work on my GPU.

**Comment by kijai** [comment]
Attention mask was added for sdpa, as otherwise the padded tokens screw up the results. Before adding that I did get identical results with sdpa and the varlen attention functions, if the tokens ended up being exactly the max.
