### ISSUE TITLE
Get OOM while decode with 320x512 65frames，while 1024x768 49frames didnt.  

### ISSUE THREAD

**Issue by sd2530615** [kijai/ComfyUI-HunyuanVideoWrapper#65]
i had a problem with OOM while the pipeline goes to decoding the latents.

it that normal when low resolution like 320x512 with 65frames got OOM while high resolution like 1024x768 with 49frames dont.

anyway or tricks can fix it.

running on 4080 with vram 16g

torch 2.5.0+cu124

**Comment by gtbloody** [comment]
me too！

**Comment by abozahran** [comment]
happened to me but gone after restarting pc

**Comment by sd2530615** [comment]
> happened to me but gone after restarting pc

restarting pc didnt fixed it for me.

**Comment by sd2530615** [comment]
updating torch to 2.5.1 didnt fix it either

**Comment by doogyhatts** [comment]
I am just thinking it was the way the memory was allocated at larger chunk sizes, even though the requested resolution was lower.
So it actually attempted to allocate more memory for the 65 frames instance as compared to the 49 frames instance.

**Comment by sd2530615** [comment]
> I am just thinking it was the way the memory was allocated at larger chunk sizes, even though the requested resolution was lower. So it actually attempted to allocate more memory for the 65 frames instance as compared to the 49 frames instance.

idk, but i saw one of my friend get 512x320 89frams works fine on 4060ti 16g, that comfused me

**Comment by kijai** [comment]
You can lower the temporal tile size to use less memory on decode. It's pretty heavy process still, to be safe you can use SaveLatent node to save them to disk and then LoadLatent to attempt decoding with different settings or even in its own workflow.

**Comment by sd2530615** [comment]
> You can lower the temporal tile size to use less memory on decode. It's pretty heavy process still, to be safe you can use SaveLatent node to save them to disk and then LoadLatent to attempt decoding with different settings or even in its own workflow.
i lower it to 4 and it is still OOM right there idk

**Comment by kijai** [comment]
I started looking into the VAE more and realised the temporal tile size setting wasn't actually doing anything, which is good as it looks like there's no real way to reduce it without serious drawbacks.

However I exposed the spatial tile size setting and it seems to work fine at half the normal size, for example:

https://github.com/user-attachments/assets/8e2914ea-6109-4847-a252-ea1c1f2e31a1

So this should help with this issue.

**Comment by sd2530615** [comment]
> I started looking into the VAE more and realised the temporal tile size setting wasn't actually doing anything, which is good as it looks like there's no real way to reduce it without serious drawbacks.
> 
> However I exposed the spatial tile size setting and it seems to work fine at half the normal size, for example:
> 
>  AnimateDiff_00024.16.mp4 
> So this should help with this issue.

thanks ,ill try it rn!

**Comment by 4lt3r3go** [comment]
> However I exposed the spatial tile size setting and it seems to work fine at half the normal size, for example:

i'm confused, is this the module you are talking about?
i have 16 set by default
![image](https://github.com/user-attachments/assets/296ad273-1256-4ca1-ab64-dadb85dc84ef)

**Comment by kijai** [comment]
> > However I exposed the spatial tile size setting and it seems to work fine at half the normal size, for example:
> 
> i'm confused, is this the module you are talking about? i have 16 set by default ![image](https://private-user-images.githubusercontent.com/44883288/394635729-296ad273-1256-4ca1-ab64-dadb85dc84ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDc0MjMsIm5iZiI6MTczMzkwNzEyMywicGF0aCI6Ii80NDg4MzI4OC8zOTQ2MzU3MjktMjk2YWQyNzMtMTI1Ni00Y2ExLWFiNjQtZGFkYjg1ZGM4NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA4NTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NDczYjc2YjMxM2NiMWMzOTI2ZmQ2ODJlMGUxYzAxZDU0MGQ2YTJiNzM2MTIyMzI0ZDU5NjY5YmMzYmExN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WwqG652XVKmx_OJGHONsy-ItU_3LdTQ-e-n48An5DOE)

It should look like this now:

![image](https://github.com/user-attachments/assets/ef55fd3c-5e86-48f9-a01b-c3cde33fb0d0)

Old defaults are the defaults, I added the auto_size as bool so that it wouldn't kill old workflows, as using 16 now would be terrible for quality. I don't recommend touching temporal tiling size at all, instead you can reduce the spatial tile size to save VRAM without losing that much in quality.
