### ISSUE TITLE
After generating, the video appears with only a black image

### ISSUE THREAD

**Issue by Smiden3** [kijai/ComfyUI-HunyuanVideoWrapper#66]
![_Hoda-Hunyuan-text-to-video-1Stage-v35 - ComfyUI-1](https://github.com/user-attachments/assets/3f3847d5-1718-43bd-aa87-145c12b9a4f3)

Model, clip, vae all downloaded as shown in many examples with successful launch. Video card nvidia rtx 3090 24 gb. 

What could be the problem?

**Comment by kijai** [comment]
Seen that happen for some people with sdpa, what torch version do you have installed?

**Comment by Smiden3** [comment]
2.5.1

**Comment by tdrminglin** [comment]
Looks like it's not my GPU card's problem. torch2.2.1+cu121, same black image.

**Comment by kijai** [comment]
Um using torch 2.5.1+cu124, latest Nvidia drivers, and it works on 4090 using sdpa. 

Could I get a `pip list` or saved snapshot from manager to see what versions of packages you have installed? I would need to be able to reproduce the error to find out what causes it.

**Comment by Smiden3** [comment]
![2024-12-08 145519](https://github.com/user-attachments/assets/582a11b0-cad7-4fd2-a412-745684beeafb)

**Comment by tdrminglin** [comment]
[piplist.txt](https://github.com/user-attachments/files/18051904/piplist.txt)

**Comment by kijai** [comment]
> ![2024-12-08 145519](https://private-user-images.githubusercontent.com/135516875/393593097-582a11b0-cad7-4fd2-a412-745684beeafb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTkyNjgsIm5iZiI6MTczMzY1ODk2OCwicGF0aCI6Ii8xMzU1MTY4NzUvMzkzNTkzMDk3LTU4MmExMWIwLWNhZDctNGZkMi1hNDEyLTc0NTY4NGJlZWFmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxMTU2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGE4MmEyN2JkOTUyNTVmYWUxODVmMmE1ZTI1OTZhNTZhZDJjYTFjNGRjYTEwZjcyOTc5MjliNDM1N2I0ZTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZjGqznm-wvgoDDqJhHu8M_8XBYjdaEyW0C2S0ESXpz4)

That's all? Are you sure this is the comfyUI python env? Because that torch version isn't even the GPU version. If you are using portable you have to do the pip list with the embeded python, as in run it in `ComfyUI_windows_portable\python_embeded`:

`python.exe -m pip list`

**Comment by Smiden3** [comment]
![2024-12-08 170728](https://github.com/user-attachments/assets/57da047f-1960-41af-ade4-f1678e5b858b)
I'm sorry, here's what you asked for

**Comment by kijai** [comment]
> ![2024-12-08 170728](https://private-user-images.githubusercontent.com/135516875/393611184-57da047f-1960-41af-ade4-f1678e5b858b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2Njg4NTEsIm5iZiI6MTczMzY2ODU1MSwicGF0aCI6Ii8xMzU1MTY4NzUvMzkzNjExMTg0LTU3ZGEwNDdmLTE5NjAtNDFhZi1hZGU0LWYxNjc4ZTViODU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxNDM1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDc5ZjIwNDUwODhkNzgyMGI2NTQ3NjNhNTk3MDQxY2I1M2NkY2Y2NGQ1ODEyNzAxMTY5ZWI1ZjFhNjc4YjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TOBtdeBTEy1rAWpPnnNMT6-Yyj_lO0IS_NLEnkdyXuM) I'm sorry, here's what you asked for

That does still look wrong as it lists torch without GPU support, if that was the case you shouldn't be able to generate anything with that ComfyUI install.

**Comment by Smiden3** [comment]
what do you suggest I do then?

**Comment by tdrminglin** [comment]
> > [piplist.txt](https://github.com/user-attachments/files/18051904/piplist.txt)
> 
> Well that torch version is really old by now, wouldn't be surprised if that's the cause.

All thanks to you ! One word from you worth more than 20 hours of my effort. I upgraded torch to 2.5.1 and I've finally made it run on my 2080ti GPU! thanks again.

**Comment by kijai** [comment]
Since you're using powershell, you would need to do:

`.\python.exe -m pip list` or `.\python.exe -m pip show torch`

for example:

![image](https://github.com/user-attachments/assets/5c6c50c4-222f-494a-a4ee-ab355d38b610)

Which shows the portable I have (which I do not actually use) has old torch version, the one you should have is 2.5.1+cu124

**Comment by Smiden3** [comment]
![2024-12-08 181705](https://github.com/user-attachments/assets/9b784b3f-38d8-433f-bcff-97ee6ea7d1bc)

**Comment by kijai** [comment]
> ![2024-12-08 181705](https://private-user-images.githubusercontent.com/135516875/393616687-9b784b3f-38d8-433f-bcff-97ee6ea7d1bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NzE1MjQsIm5iZiI6MTczMzY3MTIyNCwicGF0aCI6Ii8xMzU1MTY4NzUvMzkzNjE2Njg3LTliNzg0YjNmLTM4ZDgtNDMzZi1iY2ZmLTk3ZWU2ZWE3ZDFiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxNTIwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTlhNjYxMWM0ZTNjZTYzYTFmOGI0MzJlYjIyYjc4ZDBiZWUzOWUzYzAxZGM4YTQ0YmQxZjRkNzJhNjU0MmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sw5VNh5O49xlh6mldj9TRQDFsa6M95UPfotE15Bt6g4)

Yeah so to update that manually:

`.\python.exe pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124`

**Comment by Smiden3** [comment]
![Uploading Снимок экрана 2024-12-08 185051.png…]()

**Comment by Smiden3** [comment]
![Снимок экрана 2024-12-08 192349](https://github.com/user-attachments/assets/ea598eb6-5b8a-4979-8733-039bf34fb499)
I updated the torch version, and sefetensors and deleted the old versions. Everything worked, thank you kijai!

**Comment by kijai** [comment]
Ok so pretty much confirmed now that it's due to torch version, anyone getting black outputs should update to torch 2.5.1+cu124.

**Comment by O-O1024** [comment]
I try to use flash_atten instand, and it works!

**Comment by ivankxt** [comment]
> Ok so pretty much confirmed now that it's due to torch version, anyone getting black outputs should update to torch 2.5.1+cu124.

I got the totally same error when running Hunyuan with ComfyUI on a T4 GPU

Corresponding modifications：
Change base_dtype = torch.bfloat16  to base_dtype = torch.float16 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py

python -m pip show torch

Name: torch
Version: 2.5.1+cu124
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /root/anaconda3/envs/video_generation/lib/python3.11/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, kornia, spandrel, stanza, timm, torchaudio, torchsde, torchvision

**Comment by tdrminglin** [comment]
> > Ok so pretty much confirmed now that it's due to torch version, anyone getting black outputs should update to torch 2.5.1+cu124.
> 
> I got the totally same error when running Hunyuan with ComfyUI on a T4 GPU
> 
> Corresponding modifications： Change base_dtype = torch.bfloat16 to base_dtype = torch.float16 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py
> 
> python -m pip show torch
> 
> Name: torch Version: 2.5.1+cu124 Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration Home-page: https://pytorch.org/ Author: PyTorch Team Author-email: [packages@pytorch.org](mailto:packages@pytorch.org) License: BSD-3-Clause Location: /root/anaconda3/envs/video_generation/lib/python3.11/site-packages Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions Required-by: accelerate, kornia, spandrel, stanza, timm, torchaudio, torchsde, torchvision

you need to Change base_dtype = torch.bfloat16 to base_dtype = torch.float32 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py
and change the latents to float16 after sampling is over, to make the decoding easier

**Comment by kijai** [comment]
The model does not work with fp16 indeed.

**Comment by ivankxt** [comment]
> > > Ok so pretty much confirmed now that it's due to torch version, anyone getting black outputs should update to torch 2.5.1+cu124.
> > 
> > 
> > I got the totally same error when running Hunyuan with ComfyUI on a T4 GPU
> > Corresponding modifications： Change base_dtype = torch.bfloat16 to base_dtype = torch.float16 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py
> > python -m pip show torch
> > Name: torch Version: 2.5.1+cu124 Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration Home-page: https://pytorch.org/ Author: PyTorch Team Author-email: [packages@pytorch.org](mailto:packages@pytorch.org) License: BSD-3-Clause Location: /root/anaconda3/envs/video_generation/lib/python3.11/site-packages Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions Required-by: accelerate, kornia, spandrel, stanza, timm, torchaudio, torchsde, torchvision
> 
> you need to Change base_dtype = torch.bfloat16 to base_dtype = torch.float32 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py and change the latents to float16 after sampling is over, to make the decoding easier


I Change base_dtype = torch.bfloat16 to base_dtype = torch.float32 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py  and got the following error:
raise OutOfResources(self.metadata.shared, max_shared, "shared memory")
triton.runtime.errors.OutOfResources: out of resource: shared memory, Required: 67584, Hardware limit: 65536. Reducing block sizes or `num_stages` may help.

<img width="918" alt="image" src="https://github.com/user-attachments/assets/1ca164b9-962f-4c73-b18b-1157de9d73cc">

**Comment by tdrminglin** [comment]
> > > > Ok so pretty much confirmed now that it's due to torch version, anyone getting black outputs should update to torch 2.5.1+cu124.
> > > 
> > > 
> > > I got the totally same error when running Hunyuan with ComfyUI on a T4 GPU
> > > Corresponding modifications： Change base_dtype = torch.bfloat16 to base_dtype = torch.float16 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py
> > > python -m pip show torch
> > > Name: torch Version: 2.5.1+cu124 Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration Home-page: https://pytorch.org/ Author: PyTorch Team Author-email: [packages@pytorch.org](mailto:packages@pytorch.org) License: BSD-3-Clause Location: /root/anaconda3/envs/video_generation/lib/python3.11/site-packages Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions Required-by: accelerate, kornia, spandrel, stanza, timm, torchaudio, torchsde, torchvision
> > 
> > 
> > you need to Change base_dtype = torch.bfloat16 to base_dtype = torch.float32 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py and change the latents to float16 after sampling is over, to make the decoding easier
> 
> I Change base_dtype = torch.bfloat16 to base_dtype = torch.float32 in the file of HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py and got the following error: raise OutOfResources(self.metadata.shared, max_shared, "shared memory") triton.runtime.errors.OutOfResources: out of resource: shared memory, Required: 67584, Hardware limit: 65536. Reducing block sizes or `num_stages` may help.
> 
> <img alt="image" width="918" src="https://private-user-images.githubusercontent.com/42996988/393873239-1ca164b9-962f-4c73-b18b-1157de9d73cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTUyMzcsIm5iZiI6MTczMzc1NDkzNywicGF0aCI6Ii80Mjk5Njk4OC8zOTM4NzMyMzktMWNhMTY0YjktOTYyZi00YzczLWIxOGItMTE1N2RlOWQ3M2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE0MzUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZWI4NDA1YjA3Njc4ODY1MDQ5NGFiMmY5NDA1YTQxODU1NGVkNTYzYTQ4ZTBmZmFkMDhiMmZjNWQ3NmU4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XQ7a-6bE9oGSwnIH2AD4n6i878-Pgl7zHJ66umZnRUc">

I guess you must used sageattention. Looks like sageattention doesn't work in this situation. Choose sdpa , you'll get it run properly.

**Comment by ivankxt** [comment]
> quired: 67584, Hardware limit: 65536.

Choose sdpa, also got the following error:
torch.OutOfMemoryError: Allocation on device 
Got an OOM, unloading all loaded models.

![image](https://github.com/user-attachments/assets/0c51330e-0111-4e4b-bfbc-c8dd81ca7570)

**Comment by tdrminglin** [comment]
> > quired: 67584, Hardware limit: 65536.
> 
> Choose sdpa, also got the following error: torch.OutOfMemoryError: Allocation on device Got an OOM, unloading all loaded models.
> 
> ![image](https://private-user-images.githubusercontent.com/42996988/393879046-0c51330e-0111-4e4b-bfbc-c8dd81ca7570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTc4NjcsIm5iZiI6MTczMzc1NzU2NywicGF0aCI6Ii80Mjk5Njk4OC8zOTM4NzkwNDYtMGM1MTMzMGUtMDExMS00ZTRiLWJmYmMtYzhkZDgxY2E3NTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYmI0ZjA2NzMzZmI5MmE5YTgxY2Q2NTdlNGQ5MWE3MDllODNkNTk1ZmM5YThlM2M0NzI2MjBmODIyNzQ0YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aAX2dT5Zxjux6NBC2OjMoNgMPiVvh9as0J8uX90xM90)

this is the typical OOM error,just lower the video size and frame count. eg. try  320x320,17 frames first.

**Comment by ivankxt** [comment]
> > > quired: 67584, Hardware limit: 65536.
> > 
> > 
> > Choose sdpa, also got the following error: torch.OutOfMemoryError: Allocation on device Got an OOM, unloading all loaded models.
> > ![image](https://private-user-images.githubusercontent.com/42996988/393879046-0c51330e-0111-4e4b-bfbc-c8dd81ca7570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTc4NjcsIm5iZiI6MTczMzc1NzU2NywicGF0aCI6Ii80Mjk5Njk4OC8zOTM4NzkwNDYtMGM1MTMzMGUtMDExMS00ZTRiLWJmYmMtYzhkZDgxY2E3NTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYmI0ZjA2NzMzZmI5MmE5YTgxY2Q2NTdlNGQ5MWE3MDllODNkNTk1ZmM5YThlM2M0NzI2MjBmODIyNzQ0YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aAX2dT5Zxjux6NBC2OjMoNgMPiVvh9as0J8uX90xM90)
> 
> this is the typical OOM error,just lower the video size and frame count. eg. try 320x320,17 frames first.

Thanks for the suggestion, the OOM error has been resolved. While the video generation effect is not very good, and trying to adjust some parameters has not be better.

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/daebe765-c321-4d7a-9e24-dbcec87d71c7" />

https://github.com/user-attachments/assets/b2d93cfc-ae8f-4607-9b95-755314f99fda

**Comment by SistemciTR** [comment]
2.5.1+cu124 and new clean comfyui Width:720 Height:1024. Worked for me. 
![image](https://github.com/user-attachments/assets/489d3f53-53db-4f41-9140-3c3fa21effee)

I have 4090
OOM error at 1280x
