### ISSUE TITLE
Minor syntax issue causing loading error

### ISSUE THREAD

**Issue by RedDeltas** [kijai/ComfyUI-HunyuanVideoWrapper#69]
Hey, great work on this so far!

It looks like there is a small syntax issue in `ComfyUI-HunyuanVideoWrapper/nodes.py`, line 502. It currently prevents the nodes from being imported. I believe 

```py
"custom_prompt_template": ("STRING", {"default": f"{PROMPT_TEMPLATE['dit-llm-encode-video']["template"]}", "multiline": True}),
```

should be changed to 

```py
"custom_prompt_template": ("STRING", {"default": PROMPT_TEMPLATE['dit-llm-encode-video']['template'], "multiline": True}),
```

But I'm not sure on the exact usage of this.

There is also a minor typo in the tooltip text `To cropt the system prompt`

If you're not using a linter at the moment I'd recommend `ruff` it would help catch syntax errors before you push 😊

**Comment by RedDeltas** [comment]
Nevermind you fixed it whilst I was writing the issue 😂

**Comment by kijai** [comment]
Yeah I missed that as python 3.12 doesn't seem to care about that, others reported too, thanks anyway!
