### ISSUE TITLE
Is it possible to use a multi GPUs?

### ISSUE THREAD

**Issue by Smiden3** [kijai/ComfyUI-HunyuanVideoWrapper#77]
I have at my disposal a system with 4 video cards 3090 24Gb. Would like to use shared video memory if possible.

**Comment by 4lt3r3go** [comment]
i think the multi gpu support was released today from tencet, is just a matter of time that is being implemented, no worries

**Comment by kijai** [comment]
Matter of lots of time as I don't have multi GPUs to do any dev work for that...

**Comment by zazoum-art** [comment]
Does multi-GPU support comfyUI?
Does multi-GPU support commercial GPUs such as RTX series (how many 5090s should I order?)
Does multi-GPU favor combination of VRAM only, or CUDA combination and computing power as well?

**Comment by Smiden3** [comment]
![Screenshot_20241209_183209_Browser](https://github.com/user-attachments/assets/fb95cd3d-69d3-4e06-8e3a-9687457812de)
![Screenshot_20241209_183233_Browser](https://github.com/user-attachments/assets/8e9f8b47-f78b-4291-ad3e-aa09bbd2af90)
Do you think this information meets my request?
