### ISSUE TITLE
the result is blank after the model of "text to video" and ‘v2v’ has finished

### ISSUE THREAD

**Issue by simonshi88** [kijai/ComfyUI-HunyuanVideoWrapper#78]
all frame are blank

![image](https://github.com/user-attachments/assets/665e3983-8cd5-4588-8bc2-0f24db02bd8c)

**Comment by Smiden3** [comment]
What version of torch do you have installed?

**Comment by simonshi88** [comment]
> What version of torch do you have installed?

python is  3.10.11  and  pytorch version: 2.3.1+cu121
![image](https://github.com/user-attachments/assets/db0d0242-6644-47a6-884e-3b1e780d49bb)

**Comment by kijai** [comment]
> > What version of torch do you have installed?
> 
> python is  3.10.11  and  pytorch version: 2.3.1+cu121
> ![image](https://github.com/user-attachments/assets/db0d0242-6644-47a6-884e-3b1e780d49bb)
> 

Using sdpa with this model seems to require pytorch 2.5.0, I'd recommend updating to 2.5.1+cu124

**Comment by simonshi88** [comment]
wow, it works.  thank you!

**Comment by simonshi88** [comment]
![image](https://github.com/user-attachments/assets/954d9c25-b8fb-4505-b7da-7290d2d8ea0f)
