### ISSUE TITLE
reasoning slows down and is accompanied by flashbacks

### ISSUE THREAD

**Issue by lklklk248** [kijai/ComfyUI-HunyuanVideoWrapper#79]
Thanks to your contribution to comfyui, when I tested this workflow yesterday, my 16g 4070tis could use sageattn at 512*768, and I could run 30 steps and 65 frames in 8 minutes, using 16gvram+4gram, but there was no reproduction after that. But today, after you update the node, the speed becomes very slow, and after the sample node runs out, it flashes back directly, without any error message. What causes this?
The speed before
![QQ图片20241209193605](https://github.com/user-attachments/assets/69786077-3ff9-42ca-8374-0c7f6beffc60)
The speed now
![屏幕截图 2024-12-09 193355](https://github.com/user-attachments/assets/e35c7a67-71aa-4f6c-bf7a-2d0a735b8b96)

**Comment by kijai** [comment]
For speed to get that low you are running out of VRAM and Nvidia system memory fallback kicks in. It can be caused simply by something else taking bit more VRAM as well.

I did have a mistake in the code for a while that made the block swapping run with 1 block swapped even if it wasn't enabled, and +1 block count if it was. So if you aren't using block swap try using that with either it's defaults, or just that 1 block if that worked for you before. Block swapping is a tradeoff between speed and VRAM use, however it will never be as slow as what you show there.

**Comment by lklklk248** [comment]
Thank you for your reply and look forward to your update on the fixed node

**Comment by lklklk248** [comment]
Thank you for your reply and look forward to your update on the fixed node

**Comment by kijai** [comment]
> Thank you for your reply and look forward to your update on the fixed node

What I meant is that it's already fixed, but the fix itself makes it use more VRAM as it's no longer block_swapping unless block_swap is actually used, you can check the updated example lowvram workflow for details.
