### ISSUE TITLE
 The size of tensor a (31) must match the size of tensor b (26) at non-singleton dimension 2

### ISSUE THREAD

**Issue by amir84ferdos** [kijai/ComfyUI-HunyuanVideoWrapper#85]
Hi, and thank you for creating this amazing extension! I successfully installed SageAttn, and it was working perfectly on my computer for both text-to-video (T2V) and video-to-video (V2V). However, after updating, it now only works with T2V, and I encountered the following error when trying to use V2V. I would greatly appreciate it if you could take a look and help resolve this issue. Thank you!

# ComfyUI Error Report
## Error Details
- **Node ID:** 3
- **Node Type:** HyVideoSampler
- **Exception Type:** RuntimeError
- **Exception Message:** The size of tensor a (31) must match the size of tensor b (26) at non-singleton dimension 2
## Stack Trace
File "F:\Comfy\36\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\Comfy\36\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\Comfy\36\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\Comfy\36\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\Comfy\36\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 823, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^

  File "F:\Comfy\36\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "F:\Comfy\36\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 489, in __call__
    latents, timesteps = self.prepare_latents(
                         ^^^^^^^^^^^^^^^^^^^^^

  File "F:\Comfy\36\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 219, in prepare_latents
    latents = latents * (1 - latent_timestep / 1000) + latent_timestep / 1000 * noise
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~

**Comment by kijai** [comment]
> Hi, and thank you for creating this amazing extension! I successfully installed SageAttn, and it was working perfectly on my computer for both text-to-video (T2V) and video-to-video (V2V). However, after updating, it now only works with T2V, and I encountered the following error when trying to use V2V. I would greatly appreciate it if you could take a look and help resolve this issue. Thank you!
> 
> # ComfyUI Error Report
> ## Error Details
> * **Node ID:** 3
> * **Node Type:** HyVideoSampler
> * **Exception Type:** RuntimeError
> * **Exception Message:** The size of tensor a (31) must match the size of tensor b (26) at non-singleton dimension 2
> 
> ## Stack Trace
> File "F:\Comfy\36\ComfyUI\execution.py", line 324, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "F:\Comfy\36\ComfyUI\execution.py", line 199, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "F:\Comfy\36\ComfyUI\execution.py", line 170, in _map_node_over_list process_inputs(input_dict, i)
> 
> File "F:\Comfy\36\ComfyUI\execution.py", line 159, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "F:\Comfy\36\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 823, in process out_latents = model["pipe"]( ^^^^^^^^^^^^^^
> 
> File "F:\Comfy\36\python_embeded\Lib\site-packages\torch\utils_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^
> 
> File "F:\Comfy\36\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 489, in **call** latents, timesteps = self.prepare_latents( ^^^^^^^^^^^^^^^^^^^^^
> 
> File "F:\Comfy\36\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 219, in prepare_latents latents = latents * (1 - latent_timestep / 1000) + latent_timestep / 1000 * noise ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~

This is unrelated, but actually my blunder with the VAE update, should be already fixed if you update again now.

**Comment by amir84ferdos** [comment]
thank you, now it is working
