### ISSUE TITLE
Seed question

### ISSUE THREAD

**Issue by joshilita** [kijai/ComfyUI-HunyuanVideoWrapper#86]
I see in the examples that you use multiple fixed seeds like 3, 6, and 13. Does keeping it fixed on one of those seeds improve quality or is that just what you do? Would quality decrease if I were to set it to randomized seed?

**Comment by kijai** [comment]
I just use fixed since I'm mostly comparing other settings, nothing special to it.

**Comment by joshilita** [comment]
Oh alright, thank you!

**Comment by joshilita** [comment]
Oh yeah, another question. Is the prompt template just a prompt enhancer? and whats the difference between the STG-A and STG-R

**Comment by kijai** [comment]
> Oh yeah, another question. Is the prompt template just a prompt enhancer? and whats the difference between the STG-A and STG-R

Sort of, it adds a system prompt. The final prompt to the LLM encoder then includes that and your prompt. The results of the encoder are then used by the model directly, without decoding to text again in between.

STG-R is residual skip, STG-A is attention skip, they are different methods to apply STG. Currently STG-A requires using sdpa attention, while STG-R can be used with the varlen attentions (flash/sage). I don't know which is better for this model, I also don't know which block is best to use, it's all very experimental. The biggest downside is that using STG halves the speed and uses more memory with this model, this is why I added start/end percent for it to mitigate the speed decrease, you seem to get most of the benefit even doing STG just for few steps.
