### ISSUE TITLE
[Request] ominicontrol wrapper

### ISSUE THREAD

**Issue by EMwavelengthlight** [kijai/ComfyUI-HunyuanVideoWrapper#9]
hi,
  It's been 10 days since ominicontrol model was released for flux, i know it's not a place to ask this,and i apologize in advance, but to get your attention, people like me are waiting for ominicontrol wrapper in comfyui, again this just to draw community attention towards it.

 Link: https://github.com/Yuanshi9815/OminiControl

**Comment by kijai** [comment]
I've seen it, I wish I had all the time in the world, but I do not. Also, while I understand being impatient with these things, and I mean no offense, but this isn't the time or place to make requests, I have enough issues open as it is.

**Comment by EMwavelengthlight** [comment]
> I've seen it, I wish I had all the time in the world, but I do not. Also, while I understand being impatient with these things, and I mean no offense, but this isn't the time or place to make requests, I have enough issues open as it is.

@kijai no offense, no need to act like jerk and think you are something, i never make requests in first place this was the first time, i don't care about your issues or time anyway, next time talk with manners or do not talk.

**Comment by EMwavelengthlight** [comment]
@Bocchi-Chan2023 dog of kijai?
