### ISSUE TITLE
Black screen with the new decoder 

### ISSUE THREAD

**Issue by sx2008ox** [kijai/ComfyUI-HunyuanVideoWrapper#94]
I have triton and Torch2.5.1 working fine, but with the new decoder every output comes out Black screen, change every sitting in the node but nothing seems to help!!

I had to reset to a previous commit: 9a4abbc, the old decoder works fine, any Idea what is happening

**Comment by kijai** [comment]
Check that your model loader is not set to fp16, previously that setting wasn't working fully, I fixed that, but turns out it will cause black output if set to fp16.

**Comment by sx2008ox** [comment]
it works now, thank you so much.
