### ISSUE TITLE
Image to video?

### ISSUE THREAD

**Issue by lunatico67** [kijai/ComfyUI-HunyuanVideoWrapper#96]
Hi
Why is there no image to video workflow?

**Comment by huanggou666** [comment]
they haven't released the model yet

**Comment by Smiden3** [comment]
https://github.com/Tencent/HunyuanVideo
You can follow their development here
![2024-12-10_15-37-55](https://github.com/user-attachments/assets/88e33bc3-628d-4383-9a20-cf7d91aa49c4)

**Comment by kijai** [comment]
We'll just have to wait for now.

**Comment by lunatico67** [comment]
Hi
Thanks to all for the information.
We will wait for it to become a reality one day.
